# ----------------------------------------------------------------------
# This file was generated by D:/Workspace/GX1/G1XAutomation/sim_desk/ui/encode_bitmaps.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

AppImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAACS0lE'
    b'QVQokZWSP0iUcRjHv79/7/97705PuiCCzMMrHESTGhIHg4YQwkFcItraXJobGqPWjFoEKarF'
    b'IQcNvLNUNAkVxDAyKl7lSvL0vLv37v3f4HG7z/QM3w/P83x4yPTiGE5THEB76yVVC8DqTlDz'
    b'fY9o3PYCJ2CypFJmShERTGWQ7bJvFVY4gIQWOKyupl2FeZv7x38sG0DKTBoy52GFKXFJyCEg'
    b'QtaYAEBNuzOzO6+m1kn6mB1U+rr6jE6FqIQpmhcTgRkYetIPwwZg7/5rP594l9vOv1kDMDk+'
    b'EteS5ZLtVx0q+WoVQIIL16G0Aex61YW8pXXYAB4/HCFuzHJLQhUslBmpo4roryAspugyAAqg'
    b't3eQ9Vz4Mf/tyaPBgevdJVSbTqLAc4KwVqvWD7161QFAphfH1qfGAVTKvplUKeVh6AOglAMg'
    b'TDohhZQQImrvv8UBtAzdW82t+oXtO0PDh0dOJbQJlU9ylGlMyIK3Gnpc0aiLAgcQLM91MXsn'
    b'cjY+z2h63HHt5kqU6AC4SB+rQta8tss9HMCN2w+2rL3XX5+eOXtt9O79pflcFLqESohUSjSZ'
    b'pwy1I9FS083iT+sLBfBr6/vVi90Tz16+/zSX+zDbls5SKd5Mq3IqZuzrZtH3eUNr/81Rw0hv'
    b'L05kEpmPGwuddjl7LksUlQaaIWum6SZTRDGM0mGlAVAq1pYn11d/v33+Ir+Zn19YQqaSNpOa'
    b'pCsCRowqehJATbCG1pYo45T2rgwMA8Vi/QAA57x5dxjGT5riUdEqrJDTvvd/JTbpDJpga2MA'
    b'AAAASUVORK5CYII=')

# ----------------------------------------------------------------------
NewProject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAedJ'
    b'REFUOI2lk09oE0EUxn9vsyB6sIKlJV5yKSKIBAkiQtGDrQUFES1ejIgtHoolF4XqQSQJhQqK'
    b'IlEsCkKJBKxaQQRrb8VWPEgN/sGGHIwm0IZWVzRxdmkYD2nXbqJF8YOBYfh+b773mBExfPyP'
    b'jH8xn2gN6tozWZ5g/ELIY9jZ91Ki7U110JLOjxUFMXyI4eN+b4uu1aepUR3r8Gun/FTPTCb0'
    b'xaN73H2sw6/F8GECjMdDelt3F/bsIMpSKKVQlkVDYD8An19lKBbmyOTm3L2nhbF4ULeevF4X'
    b'MXrsDKvVNGuatpDJ/YI2BhopF1+T/+FfHKIDqJm6FU/dBiAyeJrYQBcAiScDhHuqyW4+S4uI'
    b'4ePRuaBuOx7x3P746uU/zc4jE8D+ZoOyMJt3A/Dx/TT7Ij0rgpZlMTGUqhZQjo3ZvIsd9/pd'
    b'w/NNfSzMjv4eVjAxlKLzyhsxAEKHolBxABjeu7bqqlQwG9tAKc9aDrstdKaHkTSAAKBKNluT'
    b'/YBmKnyWhfxI9WbWeWC3QOlLmeThDSBQsBxutDcAQvhunuy7D0wmR9z43beyLgyL72B973at'
    b'NQiaSwcDnHqQAxHQMH/thQeolQkwn6iaVh3ZrAtfHb5bJew7b1cEPQmWpA+0uB9HHmb/qsBP'
    b'NCvj4yBueDsAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
DBC = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAACMSURBVDhPrZOBDoAgCET59P7chDxC'
    b'OefS2JgOCh4gUg5FDv8vUqVcTfWuEm3w6Ql/TCrqqB5TfBBt8Olp9kG2CDSRK5BnvWDYILSy'
    b'fgvQYUVEck8EwGe4rDRaQiQgre5MvIltlGxUNsqJvE1kAcIb8ffwdN3DeYAvJaQAy31ARkK0'
    b't0xjCUuCvABuuQEVefmwT6SbXgAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
DIAG = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABBVBMVEUAAABxcXFsbnBtbXJu'
    b'bnBXV1RVVVJsbG5sb3Jtb3Fsb3FsbnJEREBEREBEREBtbXFEREBpa2xnamtoa2xrbnBEREBE'
    b'REBEREBsbHBEREBtbXFAWGEpodMmqd8mquEnqeErqtVpaWxqam40haUoqN8nrOImqeAnquEo'
    b'quImp9toaGtqam0to9Upq+MnquEnquEmq+Inq+IoqN4viq4iqt0nquAkreQprOMnqN4podE4'
    b'dpIoquAnqeEop94rnMwuk7wnqeEnqeEnqN8qntAqnc4opt0cquMrquMtodU2fpw3epYpqOAm'
    b'p94qnc0qm8smqeEpn9Aqns5ubnFsbW9qbW9rbW9sbG7T48iOAAAAV3RSTlMAIn1pdAYHdlx6'
    b'eJIJCgF8AoGAf3kEDQ99BX0UnXl4mAaDgSRhNEqqYB2EgRp2b7hqi3UoD4QcJT6LHzlcXWRF'
    b'O3d4fn88CRIUHiAyZm1uZX+ASHx7eksJ/iQIAAAAtElEQVQYGQXBO07DUBBA0XudiT9YsrMG'
    b'KjpEDQUSa6aipKCBGtGyAGSsJE6sR4ZzAgCUTAACgI1q+QMIaFXNKjLzNAQ0vzvVYy6MdRPA'
    b'rjbXCaDbR0BfttoO6NQdSjC0h1b168Zjl+eg6fad6p3+LNUcxLK2imouM0E5Te/3on6uCcF5'
    b'5VHUvH0ZIZhHatXMC0AAbNXMTQGGAFh780OuYWgCGN7MaoZv+jkCntTnyxWQD6/lHwwFQk4r'
    b'cfHuAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
DID = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAALEwAACxMBAJqcGAAAAV1JREFUOI2dkbtOAkEYhb9ZBpYNqyDBS6KCGAsKvCTG2BsL'
    b'tTKx1FewMj6BjT6FBYW9nbHlBYixIHZk1cKoIJd1lZ2xwJhgFgRP+f/nfDn/jHjaKJwoTZZ/'
    b'SAgqEqG3yx8Pq87ny1Dh2XCSnDldkgDFZpnrxs1QgC17iZw5jTFUKkCBgJXoHDFhds1242vk'
    b'IzNo9N+Ao/EdEtqi4bkorTpQM8OEMUrNbeAr/8cre1VTWmFjsmevo4QmbIRQWuMrRdVtULda'
    b'vRsACASn6X2S0sbxXsiEU137Ztvr00DDmIwxb05wXClQbTfZii8HWgMbaOBTd+5MhmIIBCMh'
    b'KxDQ8w3qvstVrcRZ+oDHj1fCwkAMCjh0znHcZ25blyxEp3jzW3i6ja/UYIAaLlbUpO353L0/'
    b'9ioJ9PkFaYRIWDamjPQFSIBNO89idLav8bcmZeIboI2LbCRVzEZSf0QCdf8FXCJtwMeMe+4A'
    b'AAAASUVORK5CYII=')

# ----------------------------------------------------------------------
DTC = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAsVBMVEUAAABEREBEREBEREAA'
    b'AAAAAAADAwMEBAQAAAAAAABEREBEREBEREAAAAAAAAAAAAABAQECAgJEREBEREACAgIJCQkM'
    b'DAsBAQEAAAAAAAAAAAAAAAABAQEHBwcAAAAFBQUBAQEAAAAAAAAAAAABAQEFBQUGBgUBAQEA'
    b'AAABAQEKCgkGBgYFBQUAAAAAAAAAAAAAAAACAgIGBgUjIyEHBwcBAQEAAAABAQEFBQUGBgYC'
    b'AgJd90AkAAAAO3RSTlMAAQQFl6irq6mWAg0PWi4rWa4JCq1uSp4RZUGdeX2srathUqpTr7Sp'
    b'UWZasrViPZgPPp0denKtrbCxlqyzXXYAAACTSURBVBhXXY8xi8JAGETfy27ULDkknSJY2/j/'
    b'f5IWQrBZOC93n0VikZtmeAMzMPBPLqYRAWB2DmZMZn+gaETlSzWlvw/z+k4teelXgKKN7TQk'
    b'Vf3Njpu+QUsp5dFt+q6LkYyxm+oedmoEmRhP295LVq1gO8WyF1Hh3LBiaNKaD3bXO0eNuAEc'
    b'soCDMc7Phqerpxpvfyo5U0KTXVcAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
Delete = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAoElEQVR4Xt2TvQnDMBCF70JU'
    b'2xOoE6gRRBt4tIyQUbJCJtAAarKB1evH0RkfxEVQ5CrkweN714jjcULYZK0dKi7V1+oJPute'
    b'fXPOPWhAY8yAiM+aR+hXOBNyziMc04gErfV8dAPkpJRaoFPeezzxkFJaXUqZviF5JynlQubc'
    b'Iue1xK1I2Oc2/+wBbpVziz/UAXIQQnRfYowR3zcInf8hEF4P5coIVsZYZAAAAABJRU5ErkJg'
    b'gg==')

# ----------------------------------------------------------------------
Import = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJ0lEQVR4nGNgGDTAr2+/Ctma'
    b'vbr2S/j1773tO3G3DdmG+Pbs1xiihuR3bjtX3LvjOgiX9e3sQjYkEGpI6NStEiC6qGf7fJja'
    b'4t7te8AGtM45cPvynZf/Qbh6yu7DyC4J7t99O2zizvjoCdueg8RA8jC1IH0oBtRO3fuhpH/H'
    b'NmTXhU/c4Q/U/D9uwpb/CUBXFHRvO9E+/9A7FANagIyLt1/8BzkLWXPo1P080RO37gZqfp40'
    b'YdP/rP71BiDxsv6d90HqW2AGVE3dffvg+cf/c9o2oRiAO8y23AepB+kDCxT1br+98fDd/wm1'
    b'q76kNW3YThivewdSD9IHNiC7bdPthduv/ycVg/SBDQgrXvQmrXHdc1JxVNnih2ADAjKmK5CD'
    b'g3Jny4D0AwCJgTObJUST8AAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
Export = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABKklEQVR4nGNgGBLAIaGBwyqh'
    b'ysA0ItvZwCM63tQrVII0AxoaWOyzOlYDDflvFpbz38g9RoVkVzgXTy+2y+p4DzLEITSLhyTN'
    b'Ph0b893rFh92KOgXALpkMUma/fr25Pv17zsc2rAKu61ZbZuf5nZseQ3CIDZWzVP38+BUm968'
    b'8f+xC4/AGMTGpRmnWhDj8p2X/4t7t/+ECWLTDFMLUgdSj2LApdsQgYyG9QpeXfsl/Cbs246u'
    b'GQRA8iB1p68+/Z/dtukbWDCxbs3/Q+cf/wfRxAQqSN22o3f/pzWtfw0WiKlc8X/T4bv/QXR8'
    b'7arXhDBI3Ypd18BqwQaElyz+v3D79f8z1l8gCUeXL4MYEJQ/73948aLPJOIvoYULnoMNCMiY'
    b'rkAODsqdLQPSDwDDwzAdVHY5kQAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
viewproject = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAoElEQVR4Xt2TvQnDMBCF70JU'
    b'2xOoE6gRRBt4tIyQUbJCJtAAarKB1evH0RkfxEVQ5CrkweN714jjcULYZK0dKi7V1+oJPute'
    b'fXPOPWhAY8yAiM+aR+hXOBNyziMc04gErfV8dAPkpJRaoFPeezzxkFJaXUqZviF5JynlQubc'
    b'Iue1xK1I2Oc2/+wBbpVziz/UAXIQQnRfYowR3zcInf8hEF4P5coIVsZYZAAAAABJRU5ErkJg'
    b'gg==')

# ----------------------------------------------------------------------
viewprop = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAoElEQVR4Xt2TvQnDMBCF70JU'
    b'2xOoE6gRRBt4tIyQUbJCJtAAarKB1evH0RkfxEVQ5CrkweN714jjcULYZK0dKi7V1+oJPute'
    b'fXPOPWhAY8yAiM+aR+hXOBNyziMc04gErfV8dAPkpJRaoFPeezzxkFJaXUqZviF5JynlQubc'
    b'Iue1xK1I2Oc2/+wBbpVziz/UAXIQQnRfYowR3zcInf8hEF4P5coIVsZYZAAAAABJRU5ErkJg'
    b'gg==')

# ----------------------------------------------------------------------
viewconsole = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAoElEQVR4Xt2TvQnDMBCF70JU'
    b'2xOoE6gRRBt4tIyQUbJCJtAAarKB1evH0RkfxEVQ5CrkweN714jjcULYZK0dKi7V1+oJPute'
    b'fXPOPWhAY8yAiM+aR+hXOBNyziMc04gErfV8dAPkpJRaoFPeezzxkFJaXUqZviF5JynlQubc'
    b'Iue1xK1I2Oc2/+wBbpVziz/UAXIQQnRfYowR3zcInf8hEF4P5coIVsZYZAAAAABJRU5ErkJg'
    b'gg==')

# ----------------------------------------------------------------------
viewcontrol = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAoElEQVR4Xt2TvQnDMBCF70JU'
    b'2xOoE6gRRBt4tIyQUbJCJtAAarKB1evH0RkfxEVQ5CrkweN714jjcULYZK0dKi7V1+oJPute'
    b'fXPOPWhAY8yAiM+aR+hXOBNyziMc04gErfV8dAPkpJRaoFPeezzxkFJaXUqZviF5JynlQubc'
    b'Iue1xK1I2Oc2/+wBbpVziz/UAXIQQnRfYowR3zcInf8hEF4P5coIVsZYZAAAAABJRU5ErkJg'
    b'gg==')

# ----------------------------------------------------------------------
saveperspective = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAYtJ'
    b'REFUOI3Fkz9I1VEUxz/3nPPzd9XQH7ypIYiGhhKXBsGxwakxJIraw821xiSQFMFBGtq1yUEI'
    b'dHUNpFWKB8Z7L3o9H2bqez75Odz3u/bLRXDou5w/957PPedernOiXEdyrWrACufe4/kcQJyg'
    b'JpgIakqiiqmSJIqqYiqIKCqO9XfPXATcvH2Lobv3ARg0YThVRlIl88qoN7JBZSQVbqSKN2Hp'
    b'w2a5g3p1D6p7iDhUwkmqSmKKWb8LU0QUM4c4KQNeT+0yPr1y5dm/fHzJ+t+AQu+3vpXiV4/u'
    b'MLdxOVcovkLnLLB+t9rMjPWYGetx0GrHDUUuXDR0ekkZcNIdAOBnrRHpv2oN1EGz1sBnFXxW'
    b'oVlvIMDJaQDEEf5001BU/4HPJgBo1rYxB9+/VnnxthrB5iY56qRlwGHHA3DQ2sdnleDvt1GB'
    b'TwtPyXNwjmgP/wUURICHzxejrw4ePLmIAT6vznLU9WXAcX+mndXZkHBAHuzOWj+XE9eO+3cW'
    b'Ad1ewvKbZa6uUOr++288B6N1agy7L1IoAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
openperspective = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACgklEQVR4nH2RbUtTYRzGz4ug'
    b'PkDQmwg/QC96X+AnKIiCKF8GoUYPmpoj82nOzPY85yLTbWcP52H4mJGhFqJYKtN07Cw2V52a'
    b'up21ZWdzSrZdnTNKMOdu+MHN/3/z4+K6Ca3VvqGzOeKHYnVoiGJHb3Om12NxFIJf34DFzWR0'
    b'NmfdoQKdzZ3yr35GZ09fUdRW52hBwZNeKrXIBdHnGYSYzhQkGk/C7KRznT32oQOC5i57lnk1'
    b'tWUdGEXyZxrdLlp67Jag9tElzXQ2Euo+8u0+wQMDea7NQmV6PC8REZIw2F0F+/jXSbeLgbrX'
    b'MbwnqNdZS5rNVKbJZMfr2Q8wOlgkxa1DWYslpDdMtuO5o+avgCp5aGJTU94QNPYhKSYLIZkC'
    b'yfZD0dqGRrUWrUYzmnVGnL9yFRevlYEZHoXWyooqC1lF1GooweCcSE7MB2ByUWgxkxibWcRa'
    b'XMTI+AzqlBo0GEhcv9eCsht3sOAL5nehbwLk1EStlk0vBgWMveOgd9AYmJyD8ikNPrqZZ24l'
    b'LAkoNGl7EY4k9ubj7315MVH12JN6MR1AVacTnolprARotD8jsRr5UZQGk/vXfekDiLtqT1ml'
    b'yp1r6h7BkpRkyU9BaSHxkU+gsasfnnEvzPRkHvkuz+SdwTW2q9C7w/kiy1X06Xr9YPKNl0eD'
    b'kYKFGYLv03dsp46C9ymQFk8itlwKIXoJm6Hj8Icj+X21lHrvO+UkNzvYeI3Wk5M7WQrF8TtD'
    b'IMpVYzt9AhnuDBLCBeR4AsvBr/n97Q4XiP+P3Mk8F8VCIIbd1BFE/ApsiacgcmelBJeR/XIM'
    b'Xo7HrG8dtx7ROwcEcpKKNipbrqRQjEoVs1PRzpb+AUE1ku4MbTw8AAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
nested_projects = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAdRJ'
    b'REFUOI2lk79rFFEQxz/z3hpDQBRBbaysFAQhFkHBRsU/IJWthRwkiDEB0Yhgo5hCsLIQLATr'
    b'CJHzQFHQwiCYwsJSrYJNYPfi7t3u7b4Zi707T4gI3sDjMe/Hd2a+8x0R5xnH3Fi/gWjU+bAy'
    b'bWIO6/unb3ySfyKI84jzrF09ampmpjbc1xaO2OD+r0ucZ31lxk5evoPD6OUpvSKn3O7QzTps'
    b'vn9G8EKkoCaIM0xlmF1dgpVE0T4AJvceYsJ6uP0RuMDh42fAGaqKwwECLrDu5u3U9Q2JACoE'
    b'q7oIHrSLmcMkx0rh3uLjYbnLDxsIipRCMP+bxCqAlO36lQneO9DAzWvPuXv7Yn389TvL80+4'
    b'/2AWRNAyjHShCpAnqPM4ExoL7+pUmWDu1os+24DtpjHXBAxkGtioAYqgEDJcADV4vXmAE7MX'
    b'OHtuZsfOvX3zkc+rr4C+kLQUrGhDvo1UCd+e7qHdapLGBWlckMUFWZyTxQVpUtBuNXl0vjXC'
    b'gQak6taZVhVIRJxPkWxldUjth1IwB0l3iqoa5UDBtIMEAw+qOWl+kDQpdizhZzGJqtYBB8O0'
    b'unTMnO1CpUSd58rLS0hf0wYIgg1ELvDjy5L8AfC/NvY0/gLKnN0PqSW4wQAAAABJRU5ErkJg'
    b'gg==')

# ----------------------------------------------------------------------
folder_expand = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAASBJ'
    b'REFUOI3Fk7FLw1AQh7+XdMgWwcXRIX+AUFyLq2QSHHRxsCIoRdycnJycFMGlKEKWLHYM7sW6'
    b'uekiTk6CUJ50uZRCHNLGPJPYoYIHbzjufb/3u+OeUpbNLGHNRP+FQC2fdE/rST5vHD2qqQrK'
    b'slGWTaflJT+j0/KSSb3yKMume1JPlpvbAIgWRATRGtHCx/ND4dHG8bezGkDMCJwlAJwFcHKX'
    b'F1c2DPj+cr9kBkNA3qe2C/D20i8KSOrdKEQXZ6UC7rzL7aGbDTttYRAbAlH7Bv9g71cnWmt6'
    b'QTh2MIwnPojaIf7uZsGRAQv0gpD18ydlOIiCO/ytNRCphnEyOGvhczAaw6uZk3J4zoCBdA8A'
    b'rne8pJLMRfPq1dhO9e+/8QuXxXaky0KHpwAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
folder_collapse = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAYpJ'
    b'REFUOI2lkzGOFEEMRd+3e4EMREJCRAQSEQQIJC7BHYgIQEJChKSbcApigj0CAZtAyBHIWcRO'
    b'z3RX+RP07OwQICTGUqnkqvrf5W9biuQQi4PQwLDvfD5+YDnw1n/y9ov+yaBIFMnJy7su2y7v'
    b'9pNXd3xx/9elSE6PH/nh83cEZlr/YtqsmX+uGM9XfP/0gZ5iKCgLhXFp97slBc8Mww0Arl2/'
    b'xRVPxM0BonP7/lMIU1UEAQiicxov/PjNVw0ADeE2IhJqxA6sNZ6FFNidsCkSUWgW3XkpYuug'
    b'+WwRxSIzoDoiwEbLMYHABoma+14VWof1DyqSsEAT5gjRQWaBCsqgxDRm75Vx0wv6OdGXN2Gw'
    b'VhBGfWkVR2I3gkIO2jRfEtQsvDlDFsoCx7bDtM3KqIEU4AIVvWJPg+qojQukNdAALkoQDkRB'
    b'aKcRMq3ta1DgWqFuSKhaEz2J6Asgg2qFvJVEoqqWgBfD9PH1PYePKM1UJCqh6NCu4hxRJZKw'
    b'E2g8e/9NfxD8rx08jb8BRl3Uh7llrr4AAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
wizard = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAHQAAAEECAYAAAD5zxBSAAAAAXNSR0ICQMB9xQAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAAZdEVYdFNvZnR3YXJlAE1pY3Jvc29m'
    b'dCBPZmZpY2V/7TVxAAAjCUlEQVR4Xu2dB7hVxRHH99FBRJoFUbASsINgN9gQQwiCImJUNBoj'
    b'KiSWEFuMGkKMDYwmUZHECihRCSjW2I2KChHBQlOwICpI7+VlfsOd67mXS3mwvM09b+f77nfv'
    b'Pefsnj3z35mdnZ2dU/KrX/2qVMhFKl4OVKlSxU2dOtVddtllruQPf/hDaa1atVwEtTgBLSkp'
    b'cZUqVXKDBg1yt9xyiys5/vjjS5s2bepWr15dnE9UwVsNmN9++6374IMP3IABA1xJ27ZtS2vU'
    b'qFHB2VK8j4+ELlu2zH311VcqoQJwJZVOVG78FB8PwA4MjfQXKMdP8fIgqV++h7Z4tU5seYID'
    b'EdCUdYcIaAQ0ZRxI2eNECY2ApowDKXucKKFpBxTnwqpVq7KfQi5BjnFNvv83v2yynuTvQn5j'
    b'q3ND16WM/94fJ0dCYfSKFStctWrVXM2aNR0uQRg9Z84cdS9B/K9atarbaqutckC1spTjPCsA'
    b'/M7/2EJAElTuibfDruW+1A9tqUUD6uVZ0ubDLjn66KNLAQBPEYzdaaed3P3335/tOQsXLnSf'
    b'fPKJu/32292kSZPc8uXL3SOPPOJw6F9wwQVu4sSJ2gFWrlzptttuOzdkyBD3xRdfuNq1a7u6'
    b'desW7IG9evVyH374oZZDIrn/E0884SpXrpxzff/+/d2IESMUaJ9kmoT7cn8o6T7zea/yqAve'
    b'f/nll2t8uckbcmLPPffMaQPA7Lfffro8s8022yhwfCDOmQQB/FFHHaXHp0yZsk4wOf/dd99l'
    b'GQhDGzVqtBaYXDdz5swtwmjuue2227qnn37aXX311W7RokXlwfdyuUcOoDxo48aN9cajRo1y'
    b'l156qS7JGJ199tluyZIlulwDmfpEbfG7S5cuevzuu+92v/3tb3XBdcyYMXps2LBh7vLLL3fX'
    b'XHONljdppKzdc+zYsVqGayj//vvva1kYznULFizQ+xsxDHCMj3UyztHJKIM2oRydjf/W+SiH'
    b'JoLmz5+v59OieteS0CZNmuiDAsTrr7+u6hcwoObNm+uDf/PNN/oflcp/GHf44Ydrr3/ttddU'
    b'DfP9/PPPZ5n/xhtvuFdeecW9+uqrKnWoeIhOZMyl3EsvvaTXcG/qRbV37txZQTvzzDP1Phyf'
    b'N2+e22OPPdxpp53munfvruoboABt6dKlrlOnTm633XZzc+fOdV27dnUnnHCC/uZ+dD5ZB852'
    b'ylNPPVXbs6XG6ywTyuHHWkYRoEBff/21qtT69eu7F198UY+hGgFj9uzZ+r9BgwbKIKSmffv2'
    b'euyFF15wW2+9tRpUGDbbb799Tn2MhwYmJ+gQDRs21GsYeylrBhnAnHPOOSq1PXv21A/AoIoB'
    b'7J577nGMx71793ZPPfWUthc7oF69eq5Pnz7apqFDh7qLL75YVetFF12k2uH666937dq103se'
    b'e+yx7qqrrtLx38bTcuD7FrtFFlDrnTvvvLPebMaMGQoeH8Y8CGZDqCgIxsEEwDv00EP1GNJV'
    b'vXp17e0YHXQCCEbmGx5mnOyyyy56zYQJE1SK6DAAgxrdcccdta6zzjpLrxk/frxr1aqVu/LK'
    b'K/U/nc3ah6ShWgEHOu6449zuu++eVdNIJVJsKp5r6FCzZs1yn3/++RYZr7Uh5UhrSSggQUiH'
    b'qSEAghYvXqxjnzHQJAJDiuOTJ09WsE0COcZn2rRpOWNc8vlgqEkxID3wwANqRcN06qET8Y06'
    b'RuJQ/1dccYVWgVWHhNo4j3qmI6A5IJ4F6ezRo4f+p4PVqVPHnXLKKdomqFu3bqqyOVfMlq7x'
    b'NEdCsWIheizA8IBIoEktY2dSYhmLAPmYY47Rco8++qhKKwBQbocddtDjjMcwOqlqOY7kcb3d'
    b'lzF6//3317HPJN/Ucd++fVX6uH6fffbJ3g9pRAVDXMt9dt11V/1PnA0STBsh+6ZusxUwiqD8'
    b'KZMxqNi+s4Ci3sw4ATgYA3G8WbNm+hu1hMMAwCGMIgBmXENNPvfcc8pwK4e6hD777DP9LgQo'
    b'Eoikw+S77rrL3XffffphPKXDwGg6F9KP4WMq/KOPPlJ1yf2RLgPMpkH8x1JnHLd2UCdtoB4L'
    b'rjKtU2zArau9WUBhBAYQxPQB4CBU75FHHqm/kTSYYWCjilGDlBs5cqRKgKmt5HSESa8xPdkQ'
    b'JNScBtzzjjvuUFAHDhyoQJoq/vTTT7UYdZrUExRlGsQAY9wHMLsGNc019lx0LO5pnYKOm5zu'
    b'pAHUHEAPPvhgfaY333xTAUUdtWzZUg0L6OWXX1YJtIk4vR9rE0I6kTTIjJ3DDjtM/yPZhVQa'
    b'zDR1/tZbbynjkXrGOcAzxgMo5amXc5ABQYc76KCD9NjHH3+sgJqRxVhPPaaCp0+frtdZB3j7'
    b'7bf1OfM1RzEDm6Ny27Rpo8+Cp4d5HuMZ7jcI6UTVwgAkEVCZ4hxxxBHq68XIMKk2hmONQlxb'
    b'yOAAFAMt38pMTmesbuqgXRDjJfdF8m1OSUdE4s36ZhigE5hVi7uRjmH/kWhzWhQziMm2K6A8'
    b'NGBYz3344Yfdu+++q+qPMQ4JwXNjFifzTiQDohySm+zlJkmoZ67DKVBo/OQ6G7dRoUkpxnmA'
    b'cQSZeuW8SRmdBRVNWyGmPKhUOhltQp1SR1LFMu4mOx3W8vDhw7PXpQFUBRRpgBE2PaGHG3Pf'
    b'eecdd/755yswxgzAMecC5Z988smsdcv/pGVMOZsC5TMMwJFwAy3JbMDA6oVYHOCcAcpcF0Iy'
    b'6RBI3rnnnqvq2KYsqHCrr0WLFjrVsrnxe++9p+WpDwm3zpkGQCvL+HIdD8aEmx6Oyw23Ha46'
    b'JOCf//ynqkuYb8T1TPBh0ODBg9XnynmTQr4BhGNMZfA6UaaQlKK+kS7qSI5nNvUZPXq0GmlW'
    b'P50O6xVHBcYZ05IbbrhBVS334BjjPO2iY9F2VPuzzz6r0xvKM3SgumkjfmecGcnOVGzAmp+b'
    b'Dp5dPuMhUKVJfyZMXJfRADMAw9ZO88Gym9j5QkziXtwTxmNQ5ddB/VzD9CVfpXOOTkj7KJu0'
    b'rlHxGGwGEtMewE4uw3GMZ+A600zFBqS1N7l8lrMeWqwPVNHbvc710IrOmDQ8fwwSSwOKiWeI'
    b'gEZAU8aBlD1OlNAIaMo4kLLHiRIaAU0ZB1L2ODkRC3hl4qe4eJDfH0sk6q006adNWYetEI+D'
    b'm5UlxltvvdWVdOjQoTRNC7wVAsG8h8SPzYrUjTfe6Epat24d88KloBewUK+ZxK677rrStGwD'
    b'SAEum/QIrOmOGzfOnXHGGa6kX79+mkksDdsANokbRV4omeuPdeES2RKguf7SsA2gyLHZpOZb'
    b'OCrhNdlcf7Y/dJNqjIWCc4AoDaJCbrrppjW5/mw3WEwPV3zp4cDOQlzpWVnHQgSz+MAsNN2M'
    b'vtzgCtNvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fr'
    b'i4AGh8BvAyKgfvkZvLYIaHAI/DYgAuqXn8Fri4AGh8BvAyKgfvkZvLa1AS0tdS752Ywmlko9'
    b'K1eulOqkzkjlwoEcQFfJLedVq6afhVWruhWVKrlNhQIQV6xY4Ro0aBBBLRco19wkC+iqkhJX'
    b'c9Uq1/uDD1zPjz5yJ06f7rZfssQtrFLFrd6EBgHmHnvs4R555BG33XbbuVVSd6Qtz4EsoEsr'
    b'V3bdp051P/30U3eWfPeZMMENeeUVd9cbb7hFAmpZJXX16tWuYcOG+gR169aNgG55LHMllH+V'
    b'M2PdH/fd1w3ddVe9YN85c1RaFwuoEKp00aJFbsGCBapKjTi+RCR6/vz5bvny5a569eru7bff'
    b'dpdccombPHmyqyZqHCm1sosXL3ZLly7V4suWLdO6OE+9dryceJCq2xS0cp/eeWd38377udPa'
    b'ttWHPUkAXSEqeWWG4ccee6w7/fTTXc2aNRU8wASgli1bunPOOcfttttueryySD3AlkhZwKok'
    b'Y/IJJ5zgOnfu7I488kjXqlUrBXhf6UD169fX63r06OH22msvrS9S2TlQcvTRR5dWFQNosXx6'
    b'yfh56rRprv3xx7tSYe7sGjVc3zFjXIcvvnAXHnywG7/11m7ADTe41q1b652QJABCwq6++mrX'
    b'sWPHbAuOOuoot590ittvv92dcsopbprU+/zzz6v6TdIPfvAD9/LLL7v//Oc/7tBDD3WNGzfW'
    b'0926dXPfffedq5LRDGV/tIpTAu325Zdfuptvvvl7o6jQ49cWw2acSA7UQFTvYT/8oYJ51113'
    b'uV/+8peuhgDerl07BRQwJ02a5M4++2w3atQoRycxQ4jz+++/v4J5xx13uJEjR2qd//jHP1QV'
    b'z50713Xt2tXVqVPHffjhh3ruh3KvqHrL3ik36FhA1UKVZHxsK1IHAehjjz3mPvnkE9emTRtV'
    b'pRDq89VXX3W///3vdcqCCoXoQSZ5w4cPd/fee68ef/PNNxV4u+7nP/+5O/PMM7UjNGvWTDtK'
    b'pLJxYIOAVhVrFVosoDXMSOttt93mBg8e7HbccUe37bbbKnjffvutjqEAzXSFMdQIwDGWoINF'
    b'dR9wwAFrOokcB0wDFOOJ8ZhrGXuxlCOVjQPrBXSlMHwHkUxoljC4fmb8O+SQQ9wRRxyhTJ8y'
    b'ZYpKWb9+/RREQB00aJACYx4izv/3v//Vem6QMfjaa6/V3x/ImJ0cI7kOkKNnqWwgJq8uCChO'
    b'huXC2HlikLSbMUOdC2NlTrlIjBSYjZXbvn17HT8ZE7FQ33rrLYchNG7cOLV+MYhsWoMEH3TQ'
    b'QSrJTz/9tHvttdfUSk6q201/hFhyg4BuJWNefRm/HpTxcCeZPjyz005uhYD69VdfqXpkfEPF'
    b'Ik2oXKSMqcYcMZwefvhhrR+wTNIAcu+999ZjQ4cOdVdddZWbPXt2dDZsgb6YI6HmWBjxwgvu'
    b'8RdfdC1FIqEHZExsIHPKZ599Vv//7W9/c4yjTz75pOvQoYOqWizWu+++Wx0J0KficQJACEv2'
    b'9ddfX1PXAw+ohD7zzDM6/8TwyZ+a8J85bKSycyALaBUxQMaIWl0mEjhXgJghavMJkczuokbn'
    b'y/9a8sHz86c//UmZfcwxxyiQzB9xAowfP16nGkw9/vznP7tZs2ZlrVSMG45DQ4YMcY8//rj+'
    b'vvjii7WOr0TykViApBPMEDVPeesQZX+silsi61hAlS4RoOaINEGVZKysIdMH1K9aunLe3H62'
    b'ivLNN98oUDAeQJhnAi51bS1OCKQP5wASylQFt95pp52m88v77rvPHXbYYToOAzhTFdQ3ZQET'
    b'cPOdEBUXpvU/+TodCzUFvB0FED5Yt3VFegxMqoTZtWvXVkYbqIDFcRzxjKkAyQfCCm7UqJGC'
    b'g5+XKcuFF16oXiU8TO+9956WYYmNFRmbvlBXBHPTum+OhG5aFRsuhVrdc889dYw1QiLxDiG1'
    b'0b23YR6u74qkhJYLoDQGCWV6gzUMiB/JmisNQYojbR4HNtqXu3m3yS3N3BQgsXYxoFCvEUyf'
    b'HF5T1wZdfz5viWoFWIA0/6/P+mNd5QxoZPiW50C5SuiWf5x4h1xALXwzyZdNCOlMOuatKuaa'
    b'THXsnC8HfKF7VWRYs4CyULVExrhVrG1aHK18838pkX+sbW5EfC0MBryFCxdmw0gAEmcCy21Y'
    b'ZDgfOL+5oBa6V0UGM2sUARYeoWMkjKGOeHcUVCFWXerIHPLwmTNdFZbDMgvW62MaTMY1OGzY'
    b'MHfyySerZVurVi03YsQI9+CDDzoWsc877zx10rMgXlZQrUPQafLvFeOQMkYRUQktJAzkWln6'
    b'IqZoccYxTmhnh88/d/3GjnV1AXojALXwTSIUjjvuOF2sPuOMM1y9evU0rmimdA6ON2nSRL1O'
    b'ZQEUZwQeJJbv6DT8x8vEvXAhogkqOqkossoyNeM831uWwFjYRr0uF6YdID7amTLV+FgYWTkz'
    b'DtpYaMyDseaP5fvrr792//73vzWqAcYTBQj9+Mc/Vskk+PoFWdFBQs3dR53JKAeLvOeYxSah'
    b'tn/0ox/pAvnuu++u6ht/MsFn3IsYJ4iylFtXO+18GoO/s4B+vtVWbpkwv9m8eWuYgjNevvcS'
    b'yR0tvtXqwjzGve23397tLGGerH0CHp+tpCzEPJNzMP6WW27RaD78uhZw3bRpU/1PkNhNN92U'
    b'dSzMk3syvgI8AWPUiVOfY7gMAd1idw20bbbZRp3+gNa/f3/3igSFW+wvqpcwGMpTN8DxYQ5M'
    b'G6mb88yF0xa3lHX9sZflMomWJwa3k6i0hcIsAH1JIgz6SfTBoyLB1/361+7EE09U8MZIeCdr'
    b'nzAEH+1YUcuEYeLeI2yTYLF77rlHwWDcNLrssstcly5dNISFUBYk+Pzzz9d4XOjvf/+7hrAM'
    b'HDhQ10shJPnUU09VtyEdwQhp57qXXnpJF9YJGWXl5y9/+Uu2LBESdC4AZYUH4Ok4xAXTec49'
    b'91wFvZj9yQVdf9VEKkbJ+ie0v/TgBdKTT/zsM/0/Tsa6vaRHAyaqEnV64IEH6liINAAKAdYt'
    b'WrRQI8i8QCytEdlgxLonkm1ro6hFJB4wUdMTJ050P/nJT9yuErUPmKy1sgaLBujevbsuq+ET'
    b'hqiHjy2Ecw3j9a233qpl35AtHJ/L+I+Kpt20Ew/VWWedpWAipYzHFlecbWSR/8hOW1gmm5IZ'
    b'R5FSJPYQYTI0RcakjrLcBTNhyG9+8xs9zoJ2coxDWnr16pWzfEYkA9F8ENENLJmZNFBf20x0'
    b'PoYTa6VEQgDUz372M5VcPvxHqgD4/vvv17quvPJK/Y1hBdFL0Q7EDRMfTF09e/bUc3Q82mlR'
    b'hNT5i1/8Qs8RTpPc0lHkeH7vyyWClnnoPAGyhaggAG4lBtFnMuVYKsZGUxkbTUWhMlFhMBAD'
    b'AzX3mUjznXfeqSo4GT4CeGb48JtxzojjjJG234WxllhdGMxqDOeOlyh+gGDs5D5Wt22zsLq4'
    b'hgVyiAWAnUTb0BHQGKy10k7ujxZAelmQh5hSlcXS/n8HPCuhAFoiD/2+gESkAsZRNfk/TtRS'
    b'HTEmGouBwWL19ddf76655hplrEUnAAy/jWnJh07G3Rqwdh4GY5zAeIjzAE5dxB4RlH3jjTdm'
    b'95iuq16OAyhTGIiOR/voGBhoqHhrh63ypDVmKcf1xzg6XuaLUFsZ76DxwqRSkbpFwmQi5VG5'
    b'bIMgHghjwyxcC5ouSw+2oGqkBOI/EsUmJlQh4zWql30bpqatU+S7/DiOpJvUAbBJMWOrSWF+'
    b'pypLe4vh2hxAqwpDJ2QA7S5OAGiiSOhKYdQXsmGJacC7776rYxlqDbW1OT0dtc34iupmSoGh'
    b'wniHUQQRXWhhKibBZhShfu035+hQpkYJ9sYYQ2KRTtqediCts+WGcSYMo20zezdxONQW6/C5'
    b'557TcYxpAPtPHnroITU6TO1uSu8FFOaq0FNPPeUeffRRNbhwFkAXXXSRGzBggKp61CegYelC'
    b'qOLevXtnt1jQsZBkOgWxSxhof/3rX7N10/aKAGoOoPxhYy9hm9CLO+yg2/Ex90ePHq2GCi47'
    b'1G3z5s019hYmwyxTvSZJpvpgojkDjKH2n3onyNyXDxK6yy67aIgnc1ikj1BRrFY0AlMMOgDz'
    b'XYiylDFVitrmGJ0A8LGecWSw14Z4YjOqsIqT4zp1pAnotWKK8NdWE1VInC5TF9yCAI16xPTf'
    b'QUDGapwuUxsL8MKQAVgMEL4Zv2AUZbB6YTQSBEgwD2AYE026KYdFCzhMOaiPa5iqTJX0ANzX'
    b'wkIBi7rYV4rFShk6E8fNfUhZzqN2Ubc2RifbSaewNlKumCMoNhgkpukthPHE5q7ZELiGYJ5t'
    b'nbeNRQBk8ztjii1rcc4A5pgZTrZSYv/Nb8s9bL+LrZ/afyvPNfnn+G/3Sp6nfps2JY0o2xCV'
    b'Xy7xqEX1c4NBYmxCwBGfBNNUKQxGfSElpqpgULKHc5zzdozv/OuT/226YjG+3IsyFnuUBKvQ'
    b'ueS9kueTm6GsDmtTfhuLCsH1NHbdISgbsVSWFiak6TliTFGa0ESzpex5KvzjREBT1gUioBHQ'
    b'lHEgZY9TOC43GYu7EaGbKeNJUT9OFlAi/yy1avJ7QcYNWNRPWYEar66/EnHN7SLLVu3EuU2g'
    b'mBHro/x/SNxyrJHmOxoK8cmWwPDQmMutAvEzyKOu5SkiXPNQ8XuyZEZqVfv0kPXP82R5Cxfg'
    b'xqRXNZcfgdTSUVIXURcErTLeVFVuVZE+cvq9Kk73F2SpCprJUpkEMI+U0BN8u8vFgU4YZ378'
    b'DY51S6mKbxTXGovSBF+xlJWm8I4y8jbI5WsAFSA+kIXtSySssm8mbRuhKPz/IwmkJKSDiD62'
    b'0LP8ZEkVAZjjJGxkzRJgWVaDULcEkUER1PLDNmsUEX5SX5ap6ma2E7CEVo+AL5EyItUJAGMd'
    b'9F//+pdGLgAmsbUcJ4KOyHUiDUjcCJF9kyxjrHGmKaqu/KDZtDut5VhIjpWaakbUMGngiCwg'
    b'SBpCpaJOCb0k1x/BykQysFrCpiRV2bKHheRShIUU81rjprE1XKn1eoosRx/NI2KdEBH2kRCz'
    b'Y2ltWEQmvohoQBaTidaDyHvbp08fjUrfnLijcKwpzjuvF9BkrOsFF1ygMTqoVcZHVvvJpsn2'
    b'ByLpiYC3XPOwgmkLkQQRzPLtGOsF1IKpaRLReKhexkTULIAS5Y6kskGJvSUEOqdxR1f5QrJ5'
    b'd1svoJVkfmq7t9iAdNJJJ6ml+2vZtMTuLwKkO3XqpIYSALOPxHZzYdkCbrRwNw+gspZeL6CV'
    b'ZU5JaCRqk7x8BIYRlW6p4ciJy3msWQgVa4FaqGBUc0xoXFZINu/6tQA19x7eoWrix2WvCUSO'
    b'WwKfyab5u9/9Tq1YIueZthA7a4YQUxQi95iPsnWPUMo4bdk8kMpSeq3VFnuhFa/9qCISSqgm'
    b'W/Qg5p3MQTGCULEvSk7dww8/XLNXs0eUfZoEdlmAM2WQ6DTFvZaFuSGuzY3LZdyTVZc5Akp1'
    b'Gf+2zrxZkPhZxkbUKOMmANl+TLYaIIHE3FoQM54ki6rDUk7uOAvxkGm/57rDOAm/FFAbCHiA'
    b'CRl4JL0AKMZFi5IHTHtjEoHQych4i9uNYJZvd1rbKBJQCy2TrSuONT8m1pqfH6tbvo9Vce8W'
    b'Y4pShn0ENAKaMg6k7HGihEZAU8aBlD1OlNBUA5oJBmORO/nZks+M8x6nRXwToR8u50joCnH1'
    b'8eK65AfP0cZE/G10cyyIm06T2UBMXFJy4/BG1xUvXIsDOYHWjcXFN1CiD26TNw3yuVt+E1ek'
    b'yY99kABIytZvJaKQwG5L/IjTn9y6yawmPm5XEevIAkpsbkfJBra3hIy0kTggPvvI74bi7tPX'
    b'sia3RxinCh3LvzYhkdzjYAlZGU6Eg/h+VfozWy2KOXni/1PHyVG5lrH6pn32cTfKZ4Bkv5wu'
    b'YZu8S3QReYEEkFkiXQYw0sb/uRIcpqs0mTGYaynDhxezcx3nyLBCupwmognIoL1UFgEWSw4k'
    b'FsnJdm2R9oyppK9hcd0AR5r5z3orgWcxe3XhbrT2ZiW5boSkrhkhoSaPSfwQ4BwrbwtEeveT'
    b'lRZUMoVYkSELNqq5j7xYByI3/UqRui4Sgd9EgEK6+0s6HK4D9ObyfbTUBXWVlDitJR/RcrJ+'
    b'SrZMMqtYnlzSxbEER3gowLEAwLIcUYcs2/H2Q1LexJeurw1qwWkLGcVIa0MA9jKRslMEoPMk'
    b'hcwtkuq0lYRvsrRG6rg7ZfH7CAHlZIlkGCZroeSnZ7TtJRF/vSSn0TAJ/TxSMnpyXTMJwj5K'
    b'yhyYeSdpewG2q2y1kDU3DQPdRzQCa6ekUSXPLsmjCBe9/PLLNREVyRgJf+nbt69GTxDEnbbk'
    b'xT5Udy6gGeOHtOR8WoraI105+YoIwiYh1SjZHoFBc4OkiEP1dhFJGSR5+erJ+Z/KvphFInG8'
    b'srK1lB0r0ffDRdqh4wTAYSLxttVisOQgupdNUJmXr6NKkUSykxENAWhkA+vYsaO+hN2kkRBS'
    b'sprxTu+4NLcBCbV30t8mkni7qMr+77yjkmrTluuEmVe0aaPrpexRe0zU8jRZB304k5tvX1HJ'
    b'GDpIOC9h7yHZvAZmtkY0EhU8Xa4dm8mY+bIksJoogWb6Oksh1C2xSoyjxP4irQRvQySRshcE'
    b'8I5vVC8B3ajfSLkcyJFQm5y8KeGY5Jl/V5gPQHacF6s3EIlqJOMaNJV3hYpkkc4c1QzQgM8i'
    b'+TRRpdXJiJkBzNQ4Wywg1DbHjACUJI4QiZLJ/UfKcYjj5nggqNuAj2BuQELZDwpdIuNXLwmg'
    b'7i0fELfjSBNXsFcUwhEB2GaJElhmBKjaETJqvKBzInG9pXijiKWUY4wk4Owd0RSmXuNrnNff'
    b'jQsaRduIFDIm8m1gWjWAxlQE2k7mkkxFkEQ+szfiXaA2NSqVzkCHyNabSI/6xBNPuG7duqlR'
    b'ROZPkkZGIDdOH63fOV/AQwSgMzIJizvJXhYcBJ3FyoXeEVWdVKP5TaBzzM+kKOdtTbtJRKGB'
    b'SsgKG6Cgzp07Z/PWo36JyI++3k0AlC2FhciOo0JRpbyYhzGWsXSkGDCXyh4XnA5YtLzHm/ER'
    b'Y0o1bkatoq4p+0WmM/xU5qFny+7wpZkcDpadk7dAkLgYw4i0qGxlJEAtq8oTKQM27hEr1lVZ'
    b'CcV4mSDGx0SJ5FudUIUA8b4w9BMxciw7J4YQY+xTMjdEzU6WMqeLRTtLgOaa1yXccxIvyuEF'
    b'OCLlk8R4wqKtJWB/KHXxOhFeVjBarqskan2yjJN4gTB2Lr30Ug3mJh6YD29+IDU66cfZ3caU'
    b'Jm6AWncnzYnL5Z1neIYakPcWyULlyjdZUUiegdvOLF6MHOabSC+uPcZbwMeRj1eI8nV5tYb8'
    b'xz2IIYXjgTF0LkHcGaOplhzDlUcYKFk+MY7sJQCWEpV9NBhKdl1MxpEL6Lrz5SasTrNOtagd'
    b'zx9T8d0yrck/n/xfqM5kuXWs5FSUpP8+BoT1BlorkPlMLnRMB8jMHDX/fPK//U7WmSy3jidK'
    b'phH38dAVpY4YgpIypCOgEdCUcSBljxMlNAKaMg6k7HGihKYVUJvEx2+ZWzNPLqJPsk+WyBvn'
    b'S+NKRnGLKQsXvL/15ptvdiWSikZWsqLmLWZIwY9XivGCvxJ5l7ZoF6+x8cXMm6JsO141cl/0'
    b'79/flchLVyOaRQnj942298IR/vo/O3aXBeNcoasAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
message = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAABcSURBVDhPY/hPIWCgUP//QWRAQ0PD'
    b'f1IwzOtwL8A0EwoTdHUoBoA0gxTgAjA5ZDUYBuAyBFkTQQPQDUF3FUEDkJ2Kzdl4DaAoDPBp'
    b'hgUs3ligKB0Qin9c8gOfFwDiy6vQK1tfigAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
save_edit = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB2klEQVR4nK2QD0tTURiH/Th9'
    b'Cz+IUI2ihEWFUUR5WeVq4qZrKEMR96/b7u7VadKwxEYWJJSZmAODTe2Obcxc17uO5grsV+85'
    b'njG4DAm88HA47/vwHLgdHafxDUUSnYMTscbAeASz2dcnQl4wmqgHxqJneCAUU23LroMd/MTM'
    b'QhZ/jn63hfbk7dQsDP2L8EAwlmRWfR+EPjePw18N5E3TAc1pL91Ho1HwgH9CY98sBkKdzWBv'
    b'/7AttJfug3BMBHzjKVbe/QEikp5B1T7AykbeAc1pL13PcFwEvKM6M6s2iLGUAbPG2sL3x25v'
    b'KCEC98IGK5T2QIyoGra2c9j+6qSwuY5wUod0bwefiIAybLAv5ncQi8s5+rsYjMQdPI6rWFrL'
    b'Q7o3A8eBuyGDrW/V8L/0DKgicCs4yVbzu5Bk3hVwpT8Dt+95k+v+OWQ/mmj1rvY/FYEbgUm2'
    b'vLEDicuTRrFio1Stc/SXn7FZtHDJ+wytnvthUgSu+afYUq4KSdcdAy/el5vIO52tXnefJgJu'
    b'X5q9XatAQqL2ptJE3uls9S7eT4nA5b4p9mqlhOynMoe/tJprMqIt8pPm0pn/UMQFj9HggW7v'
    b'dNc5RT8626uDIPG84oTm0nEpRsOlTHf+BRMX27X0JOFaAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
service = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABSlBMVEUAAACE0daD0NiD0NiB'
    b'0diD0diB0diC0NqL0NCC0NiDz9d/zMyD0daDz9dERECCz9ZERECE0td8w8uC0NeBzdSC0diD'
    b'z9iCz9aD0diD0NiEz9mBz9aC0deB0NeNxuKB0diDz9d4zMt/39+Dz9Z/ytGB0diGxcVEREBE'
    b'REB+wcZ/zdOD0diD0diC0diDz9iCz9WD0diCz9WCztWD0NeBzNOAy9J0wMhQmaZotL6AytB/'
    b'yc9nsrwISV8eYXV5xs4obX8WWG19y9N0wMpqtb4hZHgYWm+Bz9Z6x88XWm9Zn6pyv8gUV2wC'
    b'Q1oPUWcRUGR5wshwvcYRWG4RYHgnbH4ydIVttr5tusMQVWsVaYIYXHF4xcxqt8APU2oVaIEV'
    b'Wm52w8tns70NUWcTVmx0v8luusNCbHwYU2kQU2pxvMVdp7Nmh5I8antirLd1wMmrc62GAAAA'
    b'MHRSTlMAMpnb+tqYMQuemwrEwgGaBDQ1mpnZ+deXkzD+LZQJv7wJCJX+kggJBTCU1PXTkCvP'
    b'1WmhAAAAvklEQVQYVy3PPQvCQAwG4LzJndQWEV0UQRAVHVwc/O3+Dwc7COIiIjioBcWv80xa'
    b'Mxx5QkhyIA1o2PO0nCjB1Gox0gY3LSRuTKJm4LH9Cqg+JamVRkE7SGtU+pWIXNtpdnFcOXig'
    b'o03sLn2Ye9WUCIfSA+CeAft4dmSeaDnZWdZ2rRjDzC7bmAlOYpjj45GXJtYtC6CGVeWT8CH3'
    b'3oe/iQum7pJ5/beepZ8bAjZZ+1OdLUTh0Xx/wjdStr83jj81ylXyX2DwswAAAABJRU5ErkJg'
    b'gg==')

# ----------------------------------------------------------------------
request = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABHVBMVEUAAAB/fwBIrytGryxG'
    b'sCxIripIsCxHsCwA/wBGsixHripHrixJri5JsCxIsCpHsCpIsClEREBItiRGripIrSxLlC1H'
    b'sCtHqyxGsCpHrixIsCpGsCxGrixGsCpGrytHsCtIrys/vx9HsCxIsCxVqipGsSpGsCpIsCtK'
    b'rClKtCpHsCtMsiY/qipIpytGqi1IrixHryxIryxIsCpEREBJrixHqCtBfjNEREBEREBHqi1I'
    b'qitIsCxIrixIrC1KrS9MrjFIryxLqzCt1qPw8+77/fvB5LdPszRIqi2Lx3zZ6dRjuktXtz3R'
    b'68qb1Iyczo+Jy3ao2pux3qZovlHz+vFzw15fukbx+e6T0YO34Kx2xGFvwFmb04yKx3pUsDtQ'
    b'rTj3qEDWAAAAO3RSTlMAAk2n4PumSwEoy8gmNPDvMQEO5OERfH3S0Pr5+PbHb2oI1tAGJOPf'
    b'HxivFAzp3tq9gyoENaEUCQVOV3ezVzIAAAC6SURBVBgZHcG9TgJBAIXR715mGLagGH9iYkmh'
    b'mGjh+7+AlbHQgmi0IxLMIkSjk5FFlnMEqMfO0i8IGt2CYMeDvhBj3YClP+BR0pGmRB18w0yD'
    b'8SUxhYMf4nFrQ2I4XH+GQEw4GMOmcibFBA4WlMq5tEjQ2S2UCtWLBAWFU7oOaJSgVGzP6dlQ'
    b'Ku/Bb4MlEG1K5SO+CK6UY4JSuZs+ZQHXJ2mu3j15EoDRtm2eV+zlCwXIcdu9rtjLE9V/xKc2'
    b'W+sBamMAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
presponse = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACcUlEQVQ4jZVR30tTcRw99/u9'
    b'P5x36s1fA5d1lZWYpTdfCtRtiQmbmflWgTF78qnsL7D9BfPFBymSwEgjKE3QCKYPRmWml0TI'
    b'DF1mc0NzVzc3NnW3hzBERul5/HDO+ZzP+TA4CrohE4Z08JSXBcr7eMrdY48glghDRq/JTtks'
    b'FmB5y4+Pa1MyOayeMrT9krlGtpmrYUwzwH68Bpl8uv1QCbgHrCJyYodTrsf32AIAQGeSAAgO'
    b'lYAlrOdW6XXwHIuoHkFZdjk+rargCNf5X4P0RwZXaXaJvdKk4GdiCeXZlQhEg5j5NeujhLr/'
    b'nNAFBQQKGKhog7onzugxSoQhHlfZTYSTGnINeRA5I57NvQBL2NbJJlUj6ILHIhVNO07W9eSk'
    b'HZtGNzz7ivM0WZxSrpiDLYRRnHEK71cmEN2Jdk42qWMAwIJB++2yFhg4AZflWvTO9bfPPvwi'
    b'iZzhcX56nuuqpQGBnWVYMkrgj6xgKqj6KEPde0sIGMDIi1hLrGJzN4Q759tgL6xyUUJHW8+1'
    b'YIckIPIiOMJj6NswKKHN7xontb8p0QgplNAu2s1WxPUY4noMtkIbiiUZFaaz2MA6ThiK4PWN'
    b'YUHzud9emejbXzLFEF77awPy5vamYjNbEUcca7tBVORUIIwN5KeZ4A8HMPR1WB1v+HDj4Jco'
    b'AOiv9IFQvSZHtiNKdUEVCGWwmgwik8+CgYjo/fwU28mEw/fkRyClAQDEXyYGYo6YPB+aV6zm'
    b'GmQJmcgTTPAujmFBW3R7HeN9B8Upceb56R7nmzp9cL1f717q1OtGrNP/4jOphhcGK+8LVLgr'
    b'UF6jhDaP1HvVVDwA+A0rr9F+/wY4EQAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
nresponse = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAADX0lEQVR42mWTS2wbVRSG/ztP'
    b'exzH8SOunQBxA3HAVhCpoqRAWbjppiwKFY9F7Q2qxAIJJARLuwscdiAk2EEqNk6EWiGVBRRB'
    b'QkQJaqEiCBWrNCJtnJeTcWwntsfjsT1zua5oVci5q/s43/nPuecQ/M92IXgMX+Ck6HPFqMMW'
    b'smChremrebW84C6pl4dASw++Jw9uCoIjLsWezkiT45AOB8HZxLsv2noTtTt57H13Fas/LCZi'
    b'aM8cAJS7vEnl9ZfT4vgQSFGFubIBq6KBUgreqYAfYbGdbmwtZrH06WzqVEOfugvYEOyQQeKu'
    b'N85khLAflpoH1QyUp7//hVbr74s8J4nhfpl22z9Rnhn28JFhrF77GzufXUj4OWGGrLGcvceP'
    b'FZVTY7AKKqhpgW7koN/I6eW/9lIDRuXDTqSiP6gIj/S+rUwMvceFB7nshUVIP1/3kjWHJ97/'
    b'2vMZ0sOhnt2ARGuwSrvgZAkNtYHtm8VUuFmdul/kp6K73tMTXnW7jq3Pv06Q/OFHpwOvHjvb'
    b'2CliffbHJYdHOtI77IFlUnAih8qmhq2V/aknzVqqA8i5fGcCp4/O0N4eLH9x5TzZfHxoru+l'
    b'Zycrf+aQ++b6pGVh1P9w1wfeoB2mxSAcwf62jvW1amrM1Kayjp4XHjoxeqk7OoDsxSvzZCUS'
    b'nhs8PjJZ/Ok3rN8qvDja0L76lbcn+/qdaZ/PBota4HkOhZ0GclvVd3mC3x+LHpr3PjeG5bk/'
    b'5smNYHA6Euo+W9su4ZbaiI9r1dmO1EXenh4IOJJ+t8yUAEwIcixvtdZcGulTjjgDHtzMVc6T'
    b'qzYlHvE7MopdwnJBK0ZLe757BVsQlOTwISXttYtgJQFlkEq9DbdDRNNoIatqCXJJkD1Rl70Y'
    b'6pKhtS0rX2ue2zRaH51o1OsdyLeS8s4TPXLabxPtHUhHicD6L8d6Jbuve8mXog0SED/qUjJu'
    b'UUCd6b1dN0q6Sd/cbDUNAtJ0cNy5CZcyJhMCnhEqbRPX9uuJJjBzv5UXZHsyIstpryCw/qQo'
    b'ti3o7Es6pnAcnMxRYIAyc84axlTM0FMHhukiL8UHBTETEkW4mRP595qytcdgd1ot3G63Eq+Y'
    b'zYPDdM8+Bu/p5biTTG5MIVyoc1an1qpB6ULBsi6/BfM/4/wPRj1w9pu0d5AAAAAASUVORK5C'
    b'YII=')

# ----------------------------------------------------------------------
datafield = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABLFBMVEUAAAA0mdw1l9s/f780'
    b'ldszmNo1ltk1ltwAf/8zmcw2l9w1lts1mNo1l9xEREAzmd0zmNwzmNoYarpEREAnibAuhsI0'
    b'ltozmNssg70rfLJEREAmf78sfK8yhb00kdE1lts0k9Yqf7grfLInfbwpfLEpgLk0l9kzmNoz'
    b'mNsthMEogLYrfLIrdKgof7cuhsMyltcqf7kqf7csc6Uqf7kqf7kqf7grfrcqf7gud6gpf7gf'
    b'f78qf7krfLMudaUogLcnf7oA//8of7gogLkse7Iof7cqf7gAf38we7Are7Aof7krgbZEREBE'
    b'REBEREAsea0pgLYrgbgqf7kqf78cjcY1l9k1ltk2ldc2ldY1mNs1mNw1l9s2lNQ2k9MqgLgr'
    b'fbMrfrUsfLIrfrQqgLgqgLm2nV1qAAAAVHRSTlMASWUEHa7cWwIFdvTTUQE81a4DBA1dq59S'
    b'nQUUuWrb5liivxX6j4L2pGTpvhjodFq0vBn8VLxV/F24CLr8Xr0aAV7t/Pp4Ahiq3DUBCQpQ'
    b'3VOiDAkl1KY4AAAAzUlEQVQYVy2ITysEcQBA35v9IZdxcVAutJdJu8rERas2rZQ5+KQOUpID'
    b'yYZs2c3KAReJk4uk/JmdcZh9p/eeVKijSgAI7rqv3+MxrZll5IGfxMKMO1qWJXCkMqtb4z5R'
    b'ZX7zVFslXOhG90PqLbtq2tfVqPcijbVR8FpN86gY9iVt1oSBy3lUhGFPGiuTwKCWREXwtif1'
    b'NsCdSRHk/lLWTaB8cDHIo2dCWxfy168ln/U4FmDbuaff5puHZFcCmaqev5N5I8QTUz9/Hfcq'
    b'+wePJD+7QIGciQAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
dtc = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAsVBMVEUAAABEREBEREBEREAA'
    b'AAAAAAADAwMEBAQAAAAAAABEREBEREBEREAAAAAAAAAAAAABAQECAgJEREBEREACAgIJCQkM'
    b'DAsBAQEAAAAAAAAAAAAAAAABAQEHBwcAAAAFBQUBAQEAAAAAAAAAAAABAQEFBQUGBgUBAQEA'
    b'AAABAQEKCgkGBgYFBQUAAAAAAAAAAAAAAAACAgIGBgUjIyEHBwcBAQEAAAABAQEFBQUGBgYC'
    b'AgJd90AkAAAAO3RSTlMAAQQFl6irq6mWAg0PWi4rWa4JCq1uSp4RZUGdeX2srathUqpTr7Sp'
    b'UWZasrViPZgPPp0denKtrbCxlqyzXXYAAACTSURBVBhXXY8xi8JAGETfy27ULDkknSJY2/j/'
    b'f5IWQrBZOC93n0VikZtmeAMzMPBPLqYRAWB2DmZMZn+gaETlSzWlvw/z+k4teelXgKKN7TQk'
    b'Vf3Njpu+QUsp5dFt+q6LkYyxm+oedmoEmRhP295LVq1gO8WyF1Hh3LBiaNKaD3bXO0eNuAEc'
    b'soCDMc7Phqerpxpvfyo5U0KTXVcAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
did = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAAALEwAACxMBAJqcGAAAAV1JREFUOI2dkbtOAkEYhb9ZBpYNqyDBS6KCGAsKvCTG2BsL'
    b'tTKx1FewMj6BjT6FBYW9nbHlBYixIHZk1cKoIJd1lZ2xwJhgFgRP+f/nfDn/jHjaKJwoTZZ/'
    b'SAgqEqG3yx8Pq87ny1Dh2XCSnDldkgDFZpnrxs1QgC17iZw5jTFUKkCBgJXoHDFhds1242vk'
    b'IzNo9N+Ao/EdEtqi4bkorTpQM8OEMUrNbeAr/8cre1VTWmFjsmevo4QmbIRQWuMrRdVtULda'
    b'vRsACASn6X2S0sbxXsiEU137Ztvr00DDmIwxb05wXClQbTfZii8HWgMbaOBTd+5MhmIIBCMh'
    b'KxDQ8w3qvstVrcRZ+oDHj1fCwkAMCjh0znHcZ25blyxEp3jzW3i6ja/UYIAaLlbUpO353L0/'
    b'9ioJ9PkFaYRIWDamjPQFSIBNO89idLav8bcmZeIboI2LbCRVzEZSf0QCdf8FXCJtwMeMe+4A'
    b'AAAASUVORK5CYII=')

# ----------------------------------------------------------------------
driverinstall = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAUtJ'
    b'REFUOI1jZGRiZqAEMFGkmxgDCqxE/uOTZ0T2wr4Gvf9MP/6gKLh0+xODniofitg/DhYGp4ZL'
    b'jAwMDAwsKM75+otByqOYgYsLYujLR68YuL+dZZBydUMR+3xmAXYv/Pv3n4GLi5lBREOKgYOD'
    b'lYGTl4eBgYEBQ+zfv//YDfgDdf2XB69hHoTLIYv9QfIlihf+/PnH8PLRK4jNjIwMH56/Yrh9'
    b'/wWDAZrYnz//4HrggVhgJfJfSZKDgVvaEi55+/4LOFtVUQLO/vr0OMO95z8YJhx7w4gSC2sT'
    b'lf7rxlSiBNjqJVsZkgriUMQe7JjFEDz/HiNGGPz++w8jwFQVJTDEfv9FeAEtEP8TGYiIWEAJ'
    b'xL9/GTACEeZsZLG/fxmwG6CsJcBwad00ZCGGr3/+MVxadxJFTFVLkIGB4SHURUzMeHGhjfh/'
    b'vGoozc4AQbSHGZzSB2wAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
adddriver = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACvUlEQVRYhe2VvWtUQRTFz533'
    b'sVFjUIwia7EgCH5UiWAELWysxEICWokgkdgK+ncodmoqESsT0f/AIiBiLBWxERERo9ndrEl2'
    b'3869x+K9t4mLuyYbUYs9MMx7M2/m/ObOnXlAX3319Y8lvQw6dW160sHOCpwBAA2BCh4/uzU+'
    b'tdG5wl4ABmIZnzw3dlok5acRd2bmHIC/AxCFgTnnsFBLAAC7tscIAmEvc7leBrWL7Mn7zwCQ'
    b'aVFjT/m0KQASIADbRAS65sDI5YfFQpSIbxQc40TMBxJHgZiXmCSIHEAgsGjk8oNS+xwuVM7d'
    b'vfShk0fHsI1euT92qDQ8U9q7w1MpCALQiQg9CnFUGD24b/eXagMgMDwU48Xrj/NLDa2LmRCA'
    b'QQgF3r7/wq/VpQuvpi4+31gEXFg6PXagODQ4ALW0KQ80SSzUmq2Gcs3j8P7ibjLbDgoIQiCo'
    b'NrwtVJaLnWw6AgQAmqZYaih8RpDvOQHQACWhCqh5+GVCDfAKqDE9GfL7vOwI4My7+WodiXk0'
    b'1ZCubjXrm8pWZACBE4CQrJ8gBW4dAF1PwYdPZUIbDDWh08QCSyzQRLcE1D1DBSCDGR6KsC0y'
    b'uOQ7oUvG5rJZsmi+XtNK9btSoJ08uiBSjk48GBchYY4i6VkzR+4aHLh+8tiRE/M1DxLYudVh'
    b'9sWb2cWV+k1kH4mQ5kih2Mt7F592culyDIVzU3j0q54zN55MGJjlhEAJxHFUeXn7/HTn+X6t'
    b'ni4ig0HNVvfcgOxa2LDW8zMSpKCt2rw6mmTJlgKR5gBEAAzZ/bRZgNwwyOrVIhq0Ml/S37HB'
    b'HIBCZqxZnT9vCqAdJFhpWGGhUkUYhjASi8sK32Ah+6Y9sbtGoxtA+yBmBvz8bvZquTx/nE4k'
    b'NHUiwtq3z8/x88q5pu66yvUoj0Iekby0A+amtua9r77+b/0ArmZ/8KKqQ3UAAAAASUVORK5C'
    b'YII=')

# ----------------------------------------------------------------------
removedriver = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAB8lBMVEUAAABISEhERERGRkZD'
    b'Q0NFQkJDQ0NDPz9DQ0M/Rkw+Rks/REk/Rkk/RktEQUE+Rk1AQkpARUo+RU8+SE9ASEpDQ0M9'
    b'RUxARUw9REtBQ0dAQkk/RUs6SFY6SVg6Slg5SVg8SFQ6SlU8SVQ6SlM9R1Q9SFI7SVI7SFIn'
    b'X44oXo0oX40kX5AiYpojYZklYI4lYI8/RU0hZZsiZZojZZkfY5w9RkwgZJs/REweZ6EfZZ8f'
    b'ZqIfZ6M9Rks8R1A8SFE9R04faaUfaqQfaqU+RE0kYJQVc8IUcsIUc8MkYpckY5gTdsUAjf8A'
    b'jv8Aj/8AkP8Akf8Akv8Ak/8AlP8Alf8Alv8Al/8AmP8Amf8Amv8Am/8AnP8Anf8Anv8DivUE'
    b'iPIEifQFh/ENftkNf9kOfNYOfdgPe9UPfNURetARgM8RgNASgc8SgdATfMcTfcgTfckVfcge'
    b'bKsfaqg8icE9gK89gLA9ib49ib8+f64+gK4/gK0/iLxNfZtNfZxNfZ5NfpxNf5xOfJpPe5lP'
    b'fJlPfJpPfZlPfZpPfZxPfppPh65QfJlRh6tRiK1ShqpSh6qiq7Cjqq+mrLCnrbGzvMO2vsO9'
    b'xszAx83L0dbO1NjP1NjR19rb3N3e3d7p6uvq6+zr6+zr7O3s7O3s7e3t7u76+/z7/P3///8e'
    b'U8qnAAAAS3RSTlMADg8SE0lLTExhYmVlZWVmZ2dqampqa2tsgYeIt7u8v9DR1NXd4eLm6+vr'
    b'7e7u7u7u7+/v8PDx8fLz8/Pz9PT09fX19fv8/f39/f5a/MNMAAACPUlEQVQ4y5WT3U8aURDF'
    b'z8zdXb4bxYAogqQ1EttoYhqTpv//sy9tUqOgWwHjFyuwwOICe/qwa6vRtOm83DuT353JnTkD'
    b'/MPkuWNZBYfz4XL5NlAuVAfVJk46xd7o/jVQ/Og0bgUAiEp7ejJM4iY5t+s7USAqIqIytuuh'
    b'M3yRoflBVSTxSJLz87NnGZpfZyqqoqoqIiICPfD7v4Ht5kxUtTqNa0jNF8AvhKMEWKvlVUV3'
    b'36/eqojKl5IMBFCO5jHweScU1d3Gu2y6LyKH67kcB4DU5QowQKVMVW028jDZTF/2qhZSOfUE'
    b'09CfwQDrh4Fqpb4KwMpk12oWgJTOJmTjegAD69NCRIJK2gCw7JIBgMA/I+BnOjSwCyuqKtdO'
    b'3gCwBQAC9zsAsDuIDIpNFVFVLyYAILhsgSSRvX1UOM0kfNqbx5fZZTtp8X4OCv5dAwZpx8Qj'
    b'2qvZiSyyeIhIklfuo8HCWlERkcOq9fTKLth3ZER2biLFsgiSPNqwAGASAUC6dkQC2FhAsexV'
    b'SK7b8f+7rQAA0qZMcrNNGMCxbZGJlUsBwWXbQ8EChm6XpHsxhwEm5Xog8mCyqZnbIh/snDU8'
    b'PydZ6nbiaY6XeUA8dXqnIKO7Yui2GUX8cbaIgUerqAC88AIEye7CZUSGXe9JUUM98AHxGcuR'
    b'QzLi1rH7R5OeX1ABY73GPQqPW89l3w+j7WkCkGTppOO+3IvRGPPGU43Nn91W//VcVlfqN1v7'
    b'+NbbbN+P315eNZkcJsGC+A/7BciKGoje2cx/AAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
refreshdriver = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAHl0lEQVRYw81Xe4xU1R3+zrmv'
    b'ec/O7MzOPtgHjwVWXHd9QIXGkmqw6Ss2CqJoNdZSFElLoYlpa+s/Ndg0sdk0UBtREbXAUkoI'
    b'ii1tUWhRXBdhQaCwIM99uTszOzM7c+feueec/jF3ltl1d8A/mvbO/HJubk7O993v/H7f71zg'
    b'f3yR6514w5J21RvM1QvOp0qqErQMFheExzjk2McvPXjuv0ZgwVN/rI6Ulf3C75UW1YR9waDf'
    b'5fG6NUXPmhhOmXoik4ld7Esl01nznWQq9/r7G+4/OvlqgsxduT3SMIjB7dvvZ9ckcN8vdz89'
    b'rSqw9vaWKWGf2wHOBbgQEAJgQgD5PwiAaCKD7stDiePd/WfiCfbrf65fvGP8el9Zvf1FnuMt'
    b'/1q/dP41Ffjuc3t+t6C57olZDSGZC4BxQECAcwEmBAQHuBBXgwMSpaAQOHVpMH2w68r7Q+n0'
    b'Dz5se/ACANy5ZsfPZtZX/PTcxcFDf3vh3kUFHHki8MXPvr3myy0NT8ysL5eF/cYgAvYNYD8T'
    b'yD8qhGkxCCEwrabcPb0muGj/kU87XGt3rAMT6Zuaan4yozrgudATH4P1OQJzV77R2jy9fPXs'
    b'hpDMuUBat3BpIMHiw2ldzxlUkR0k5NekYJlbdTkUUErBLZEnYxPSDYahlIHGqTVhTXE8L2QM'
    b'V5T5AtkcA4EoTaAmUPZwY224lnGOPQfOJI6e6aWZLHeDsYQFMkAk6ZAAvxzwq4HKMs9tDZWB'
    b'WY1TQzUul4aUbiGZthBPm7B4frvC4TKVcVERTRmoDjhACRclCVCJ313ud6JtywfptCH8Xp8P'
    b'kpw5OpQ01328cVn7+PnzVmxuOXDsysPTqrzfmNVYMZtDo/lEzW9TIp0D43mFCAEEJZMTuP3x'
    b'zTMiAZ+rfe+JpKw4fdU+LZnJ6rqRY7smAgeAjj880gWgK/7oq8/1RzO/mjMz9J2ayoqaoaSR'
    b'rxj7N1qIogQBk1JnIpkJDaUyZm115X6JkkQmk/Wks7lrGk3Xa48NdwGr4ivfaG+o0l+e31o/'
    b'ozeRheB27gKgFJAh+KQEZMFHPhtO02DQ/57boX5CCUkmFCkoCXLyep3NrTrvmdNYURvLmOBc'
    b'jIIDABGfr/oxBLilWFmT6T6Pc7dbc1wklCaC5To/f4nHrgf8rjV/XrOgtX45lVUtq+fs8rzK'
    b'gBBAgJRQIECHzIzV20wj2370+Ezji3j6wtXt329qCDxTGfJ4TUvAqaijVkcIQAkBuEA6lxMl'
    b'e8GtK96cR4SYSrmghEqSEIQQhUkUlApOKZEEJaDUkWU79728bAAAmp98MxDSHM9QGY0uVZZg'
    b'e8IoCM9rrxsWGKd/erft3lcmVKD1sW3hoFdrX3zn7PpR9ytwFAIgBNkcw56Dp3sGBf4OYAAA'
    b'jv/+oTiAtddS6Zblm78kScrdY8p+/KS6iJeFg24oDhWKqkFWVciqAllVEfA7cbEv3p8aMZcd'
    b'2bD0bEk0IUjH8WhtZ6dQrspNWonAXSUJAAQ5JpCzOHKMw2IcFhPQFAmnzscSh0/1/fyDDQ8c'
    b'uNbbPrvpPa07qrdmPANNnedifgDQVHWKpNJQSQKi0GOLk1OiMEwL+z46+86BtiWvXE9Snk06'
    b'1WjKaKaMNukGb9p/8rMqVdMWcgazpBUzgTHOBeS7nFuTcc/Cpm97HTv39gxknjq66aHuUgRM'
    b'3VNmMXGToESjYK5X3zq1VHOpMy1mdZVUQAbGmEeh1Y7oFpwuzf21O+YsuvGG8N47Vm3dcPP3'
    b'Nt4GQLLXocVVZYlM260zPNOIQNOejt4lFwcTD6gOZwRCnJzciDSDFDu3Q5GQMSxAABbn6Isa'
    b'SGZMRCoqGiKh4JNXeoa+Gfzx1rOxaHRvdmT4tOqtdSs+b1VNKPT1b91SPnffkR6163y0diRr'
    b'SuUV4XA8OqybZm53yS2wEwE+l4Kzl6Jsem1Qio2YuDCYgZHjEABGshYIgEh1RV2kKlSnj1R/'
    b'NZnQh+KG5bGyJkmPxMSWfbGcommm06FVBoMecAFks/qJhJn5aDICNN13WuP1lcShUnR+cjn6'
    b'1/2Hfxuprlox/+bGWlmiyJoM3LZXLoB01oIQAJc04gk5wh57y5gAGOPOwpmAC2A4GkuNDPWs'
    b'O/36D5m9bQz2TSEXtGBlc6BuxqxHJZlqb/+jo61z86qt3Qd3bjOCLSFVoVOqQgGHgIBpXT2c'
    b'ctv1GAcsLuzg4AJ2OwbisaiRGux/8fCmlVuKHFgA4FKRErK/prkMZfWPnOq+8NahjSvWA1AB'
    b'rlw+vLsjmjCPJS13FeHE6/c5NFmRAZC8GvYBdWzzETCMHKIDQ7FE77nfdL626qUCaOH0BoAV'
    b'CEgAJPfUFo/mKnd9uHH584VnhUj1noxf6tz1biyePJbUZSRGsl7CuQCIRgQHEfm1s3oOyWSG'
    b'x2Px3uH+vsOXO3Y9/e+/vHDAltyyx9EgRZKoE4RiR/G9nA9Jqp13343OYF21O1AxRVIcfkaJ'
    b'EEZ2IBPrO5HqP/dpX9eubgA5AGbRWBxsfDdUJweEMk4VOn4/7WBFb5srGovDtOdO+GFCigDl'
    b'opAmMB0ytngnJMHGEeFf9OO0ACxPAE6KwFGUYGxcCPy/Xv8BXhvn+FFtPd4AAAAASUVORK5C'
    b'YII=')

# ----------------------------------------------------------------------
device = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAASNJ'
    b'REFUOI2lkT1LA0EQhp/d9Qdc4Z+4xiIINia5w9gERHsVUlpaXGfAK7SzFgsLi/wCA2mi5PCj'
    b'EZEgiKUBW62vkrU4d7nNXY4DBxZ29mWeeWdHXI/fNGnKotjeWRMLRWCJNCXYWCkVk9vXqto/'
    b'gMwabHVPHWE4OsJoVSGRyia9OKAXBzlVFSsKDpTMbp7HdIa9A1itEmC6eB7TZOYCajmQWZfh'
    b'+W5RlbUcSJKnj3K1BkCIGjarHeQi9Bt68v5idzd+nujOIALgZu+MzdVQtJp9XQoI/Yb+We4S'
    b'+lhIZxDxcHAIwPpFhCGbVV/FSQYwxQDzkMfvT9fz3LqdP2g1+/ru/qR6hP1LZwSEVPa028c6'
    b'n9c5zicaFwDqa4QZy0TZ27/X+AtwAFh3sk5R1gAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
resource = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAGSklEQVQYGd3B+1tT5wEH8O97'
    b'zgkBwkVuQaQVRKXySKWIBatMaMWCVK2DlnmpthPxsfbBYrHq3EREHy9FdOiwpahYqVi1Ku3m'
    b'Khqc9UKUS0XkEg0CQqAJl4Tk0CQnyTnvnv0N20/7fIiqUlWpqiSZqIMKKhqBmYhGNIphgB56'
    b'cKhFLWrhSulM0aRo8P+HqBJVM1RRYc/JF+wKVjusED9Uxj9z2fx/3fvrKfftTBl/3qwVN+C6'
    b'XOeZykZDxnKyDPIVIHjw7c4lgDvje0T2OeDihGeSEnDcsW6UtIBHjO867hQgbZYu0FxAOmft'
    b'Z8xwPj9n3tYdg7DqmsYfVX+nb5Jb125du3VtRzbTwTxh2rp9kIMc5Fw8Ch48xplHGMYwhqTY'
    b'5NnJryfPwf8caUluuNick6Dv+eA3jWHfXqpJMm5vdT4dFKrFO7Jd8qXQ0nlcNhXoCFFKKxBI'
    b'H9P70gGASYeFrQfEQgjiWYAxkIdMPsAsxQJmF+CcL/U74wFykHSSLATIk9mZ8tepOHh6LNOQ'
    b'JTupKmr/RH2/eynHtwrH+ONi6ssj3lsmrn2r0i/T9ydj26LZvQpdTI8Bx2uuVPY2qZAR71jo'
    b'iFwETF4zTR9cC/zL/n3h/TXAYtta87xSQLOtOeVFJNCovH1GOx1Y1ZOLVB0w1mB6YC4FauVn'
    b'E+5coHk+j+OGSQSJ5p2uSn7iIwNHD5D3yUr61C2XrefmSq+KLA2gmWSpwchHjO+mwS+m9tp7'
    b'ayBNCRzVK9UQFX4hks8+oK9wwDB4DDC9Y10mOACesSc7AAylmKJGh4A6Y8dHzQsA06zRAlMF'
    b'wrrv6U/pUunlQKVpg9dU7q90HXWSYnEOafvtcVer52yNIYnfY/Zv0D2zjl1vcLILO/jhOMt6'
    b'XJn8R6+ykABkCBrXCcdGYPiAPc9yCAi960OCBoG+ieYYgx0w1vDpppcBmuNaLx0Crh/r/Lz+'
    b'd4DyhpfBbxfwxqbwT1+dTz9V3+t1tIWR0uG2cZ/Rxb+YmMja6HejJkNxWXXmg9PlqNec+6Xo'
    b'ri+ACsNE/Z9AbQ22kxYNwHxm/mY4CLCrtc87RoHW9iG+vRPQL1cfVc8BhO096dqzgLlEeINP'
    b'BOKqPeMmTAFeqefG3KYC5nDbn8djAHYNrPiPFFKKUIDrbXj2WdcBMsNiem1bVj+63BtlO3Xx'
    b'gLLFI9BSLPIj6+wZllhcGf3IvNCYBmV/jDDDthN3x6We5u5/kMwgfeAZHw0TaV8gTXBcgM1n'
    b'GSkkRfCQv8b2MbGA84jLJhwG6Ep62iUgiVGTl0gCQN+nifhWCufku42Tu+UI7jumrEwqowWD'
    b'l8dDyCX4pmdrUrfI2LdGLisyXU1YbJ4k3mDy4fQ/6/80KASJ/t7St+QvOGyd62qhClota5Rm'
    b'Sf0IcKy1JzF3IJI8mTnIG6DudBNtxHRxuvOI21YpxpHpqqC7WTCUXMBaNpgjEzzXK3SYIN85'
    b'FmcpYbd4zBi7bVvmeNF+VXrHdv77kLFi45fG39vflaXJiHw2G2HPdxjFq8JgWEFQoWzfKwVx'
    b'prAq2XdJW5locohbRwfYfOY8oyehriRYmUWAdFOKlmroP70Wy960t7DpTJxbGzv8pPmmsyNL'
    b'mnvpOVEff9D6sGT+lHs3Bs551y3PsPfhqsdAVXbXkPDEr65z9UibLWPUzfkotyv8h71xzCPP'
    b'PC5w/IYUyy8XUrEivUkZ5+UiCeXnKU9Xo8kyUzpJi6TrbBmnZwaYCgSBUA1OinXoJ8F0s98T'
    b'+8+uKiZhz3bfPPcd5G/lP5AHxfc/rtvgJvi4eTY40thIxVz3HX7f2V7sPHpmwdeFbOR4tSKC'
    b'lCCC3iJLiAVD5CvmIAlFqGy/hUpqur8prZypraR6ewgOu64hgNx07GUjIDrfZsOc2QAucTpU'
    b'wM37ouMTtw/RRRPfxqQlxNsaO4myGbCTlZlfxnZvBLTlxo/Zu+RhWtU0nUMgJ34cM5dN00p1'
    b'WOVaDUD3EpUVjOeDCbf4xrsIpBPxWd1+JfivkfqWe7t+HsRq982sjEYgTCyi75E/YD/5hiSj'
    b'HZxjJv919ya4DJlts0q/ACFbEQwzqFVNj3A7MNUviom2JWCR9BNNwR44oCUxzG0QnKJVYhlA'
    b'TGQ3OQhK3sM2rIK7NUqax55AvaKDDAi5aPk3CfoJt9bmBkEAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
device_no_exist = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAEySURBVDhPpZFBSgNBEEX7KO5d6zbB'
    b'C3gEcwPBCzjbrDzCZJUDNCKIyjRByCaKCCJKFnMEEbKJi7L+71Qz3SZBkoIPNV38V1NVzt+9'
    b'ifezjZJVhBCkHUWFebBncTB/L5ZrhRoiDPrSQlUVpTneEM5fP9Hc611mwhtq6EbzoBL5+YoA'
    b'/Akg+lfO37wkQN00AgFGgNbaETqq+gpRIyHI8aY1529fI+D0Ss7rhkJOgNYIgEEFMwEH8TsC'
    b'dIkEnNWZCNBa6ggQjOiMMVZA5x/eNy9Rawgz0GzjYCdcYvMh22T34uK4wLhEC5eyHZMMcHJ4'
    b'lGHunyfiLo4p5Ijy3AkAM4pdCIyPn2MKuQG65ybAzEY3CEzD6ZBKgOLc2QgAdGPtCMW5twL+'
    b's9c/gO4Y5cLKUVHf+4y/ShQrgXlNPwUAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
panel = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAHSSURBVDhPpZPdbhJRFIXPO/kIPkTj'
    b'A5h44UXjhbc1TU1MtHeS2qT+ljSjU6olmBYtBEHGlh8pCrZgW6htiRJph/8BxM8zx9BCJHjB'
    b'TlYyZ89Za529d7ZgzBBj8hFLngjB6FcCkQy+zS+8DadYDyWZfbiKEc/KcxKPL8rKWphnrg3u'
    b'PtAHPMWyN06781uiS7PVpdroYNbaTN66Ly/OQ+UenEzB7g2IXuXmzNyggL4eoyXJVrtLrfmX'
    b'XKq0uDOn45KumjuAc8XHE/0Nj557mbg2hdPlPRcRL9YiNCW5bv2iXO8o8s+yRWLnmM1PeYzt'
    b'POFEjlA8RyB2wIIe5PLE5IWA9nqLhiRXJJlLsqcS80JwVGywX6iROaqSzpdJ7pnEMmdsfCxy'
    b'5frtC4ElzwdV92nFGhDIHldJ5cokJNHhcKBp2j+w88LpNlTdRdNSzj2k8ybbkhzZPVXEXvj9'
    b'/vNvOy8WX72X7i0KpSaHPxrMTE+zc1gluX9GVD7ZSJcGBIQ06YUSePoyqNy/yZpt8jDYF21n'
    b'm9yDfVYCj13vyH2v81nWG8+ahFMlfImiElo1CiyHTka/YHbBrbraj/5p2PmRPRi6C33jtP+P'
    b'nMIwgf5p/G/Zxt7GP2vbYMI+wuv8AAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
viewproj = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAW5J'
    b'REFUOI3FkztIglEUx3/3+xyqpYYInFykLRykTZp6EEIQtAQ96AlSOAW1RKSLQVCEBL0QXJya'
    b'QnptkW1RUUvSIhWYRHwR1FWC26B9+WUG4dAfLpx7ub9z/+dwrhCaTiXSKqL/mmDM41Lfz0Rx'
    b'CUcLbsuFlulTMd/WUAJ9au4wIxCajtB0tied6rtuz/ZVoMOucq8HKn0SVov97WYc6LAroenY'
    b'AI6CbtU8Mkz2YQ1pSKSUSMOg1tEFwNN5ksz9I8nUoxlbSjgMupRnYrXE4vzgDNXympqGJpKp'
    b'L6jRUc9r5pK7N3uhiTlApktWMBYBwL82RSA0DEB4L0SfL+9s4/hCCKHp7My6VOuQ3/J6fGWp'
    b'XO8ssgFkX7IgjS94PYLX7/sVNAyDRDSWTyBzWUAW4Bje8V5LwhJYQiIao2f5SlgcxKO7eAe6'
    b'QcryMFUmbJbw/PJegDtNJz/DdRYYiiZxa9RZduKKNbJ5I4r34t9/4wdtmbFnw+TGCgAAAABJ'
    b'RU5ErkJggg==')

# ----------------------------------------------------------------------
viewconsole = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAhtJ'
    b'REFUOI2lk81LVFEYxn/nPefembn3Os63NlnJhFYIUlDRqkXUwvoHiugvKAqUNtIyaBEVSa7a'
    b'ZYEQES1CiChoVUi0VLRvCT8YRWNSx/m4La7OzY0WvXA4Lzwvv/d5OBylRPM/ZQBO9Q37IgpR'
    b'Ci0KI4IWwYhgtAp6LWgdaqIUA70nlQHIdRTI5LNEtCJmhKgleJbgWIJnKRyjcax1TSssrbj/'
    b'dDR0MDf5meLHL4j86UBhRAcOtGC0xohCRNZvFQJ6O59w6VHrP2W/d36GAUAAqjXBdSLY9VXs'
    b'+iqTL+/gOpEtT7UmoYNKXZNqdvAjfmNDqtlp9F0dbbS1pAGIRm0ACu3vQ0C5KrQkPaya4cFg'
    b'P+cu36Yl6QFw9OA+ZuYWeDcxzXw9gLYmPQ7vSYWAtZoml47jqhgAuXQcgM69uygu/OTtrM/p'
    b'48fwohYApdUK/c9KjI5N++sODNmEx7UrZ7l+d5hsItieTzfx+lOJ7q4CS8tllpbLjVjdXQVu'
    b'PHyzEUGTyrlB9oTbGPLcKBNTRaymZmYXVza9QtyxmJgqhoCsE2Ho8QuanEhjKGobVsoVvs+X'
    b'+DFf2gTYmfZYKVcCwHLV8G18pCHu350kn3VJVCfJZ+I4MZt6ymWtUgfAtoR4zMZk4qjtPtPo'
    b'2LR/5uoQPScOsfirjO8rkp7NyKsPPL95YXvABqRvcITxr8XAYXuGWxd7OHJgh/orwFb1G0FR'
    b'k5bTg4LVAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
viewprop = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAahJ'
    b'REFUOI2Nk79LXEEQxz/73npoqsSAaP4Ey0BIkxDxCIiKEY+YykJsUng25vBH0CKVELEQQQtF'
    b'Y6FBuxyIEoIS0iSFhUUgKVMkkHBwoKDv7e6bFM/7kTz0bmCYnR3ms9/dZZTyfLpH16Wt5TaD'
    b'6XZ2Pnzl1+8Ce0vDinpMeX7Ze8Y2pTqvx726TrlOwOHenJSS+f07vOj6WXdzZ+9LpQFu3h+P'
    b'd/a3K+sa9mUrB4C+MCkAmp37J9ayP4ViDDgNGmkFtB8XtK8AAVH8+Dx5JSB97xbp/Jjo0/Mb'
    b'AKS0dxkVUPnBu49fXwk5fp9DnwWNVY2VCAoXxdC51UOCwBKEhjA0hKFlcSaDizz0uUlx8DZf'
    b'pi5v5Pn+7YRisUA200QUCbmRDhCFQkCBCLgITOSjp7JPy3q7R9elOn/+ZEKsg4U3RwkF81MD'
    b'GKvR1zw0odUYEbJDjxI144SwBKiehbaWd1KahcA2YKywsvUxoeDVeD+BbYgBpcFZm/1PgdMY'
    b'J4w8ewgolBLk8o+sE0JX4wrG+bhI2Nj9lFAwne3DOL8WQOMiGMo8SNScxPW/X2PPsmLWo+gA'
    b'AAAASUVORK5CYII=')

# ----------------------------------------------------------------------
viewcontrols = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1B'
    b'AACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAHSSURBVDhPpZPdbhJRFIXPO/kIPkTj'
    b'A5h44UXjhbc1TU1MtHeS2qT+ljSjU6olmBYtBEHGlh8pCrZgW6htiRJph/8BxM8zx9BCJHjB'
    b'TlYyZ89Za529d7ZgzBBj8hFLngjB6FcCkQy+zS+8DadYDyWZfbiKEc/KcxKPL8rKWphnrg3u'
    b'PtAHPMWyN06781uiS7PVpdroYNbaTN66Ly/OQ+UenEzB7g2IXuXmzNyggL4eoyXJVrtLrfmX'
    b'XKq0uDOn45KumjuAc8XHE/0Nj557mbg2hdPlPRcRL9YiNCW5bv2iXO8o8s+yRWLnmM1PeYzt'
    b'POFEjlA8RyB2wIIe5PLE5IWA9nqLhiRXJJlLsqcS80JwVGywX6iROaqSzpdJ7pnEMmdsfCxy'
    b'5frtC4ElzwdV92nFGhDIHldJ5cokJNHhcKBp2j+w88LpNlTdRdNSzj2k8ybbkhzZPVXEXvj9'
    b'/vNvOy8WX72X7i0KpSaHPxrMTE+zc1gluX9GVD7ZSJcGBIQ06YUSePoyqNy/yZpt8jDYF21n'
    b'm9yDfVYCj13vyH2v81nWG8+ahFMlfImiElo1CiyHTka/YHbBrbraj/5p2PmRPRi6C33jtP+P'
    b'nMIwgf5p/G/Zxt7GP2vbYMI+wuv8AAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
widget = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAelJ'
    b'REFUOI2lk71uE1EQhb+567WdjRxFS2QXJJEikCggBaGhgSpCChKUPAIVL8BD0IUnoKONICgN'
    b'EmmgSBqgAOWncFCwZedHZr323b13KIxCEjZIiJGmOdL5NHM0I2IC/qdK54WN10+0s7t6oWFq'
    b'bolb95flQkBnd5XFxx8g76G2i9o22DZqu5D3eLv24u8TTM0tsfJsAQUEUAFRUEbC7PxDYPm3'
    b'QUxwpnf2uvr0+Rvd2e/pcTJUa60eJwPd2e+N9L2unvGcDnF9c0vff/7Go3sLRGWhEgqlQMgd'
    b'DDJPapWXa5vcvn6ZOwtX5Y8VtpsdphsxImCMUDJCORBQJRDBiDLdiNludk485jSg2TqiHtdQ'
    b'BefBecU6JffgdNT1uEazdVQcYvsgYaIWkTkIcgUgcCOYzZXcKRO1iPZBUgzo9YeEYQmbO8Dg'
    b'vEFE8Qq581inhGGJXn9YDKhFFZJ0gInGUFUy5xABFHKvOO9J0gG1qFIMqMfjpMkhUbWCV0Wc'
    b'/DoGRVFUIU0OqcfjxSHONCbJkhZx9YCy9AGL+hzVjFBSLlUPyZIWM43J4gmuzEzx6ctXFm8e'
    b'Y6s/sK6EV4MxnnKQUzaOV98H3Lg2e+KR89+4vrmlK+8+MhYKIjoKAEFVSDPlwd35kyMqBPxr'
    b'/QRPyuzjKsMCOwAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
run = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAjVBMVEX///8mgEEmiEFBkVde'
    b'mm86iE8ziEhmrXctiEFIkVdImlc6kUhBkU9mrW86iEEzdzpBiEhIkU9PmldXpF4tgDMziDpB'
    b'mkhImk86iDpBkUFXpFdIgEhmpGZ3rXety6260rrV4NVemleIt4BvpF6ArW+It3eawYiIt2+R'
    b't3eRt2+kwYiAzCbC6Xj///8ggEHwbmkkAAAAAXRSTlMAQObYZgAAAKZJREFUeJxtz2ETgiAM'
    b'BuCwZKgpIZQZiZCVGuH//3mBl+d11/ttz227bbP5Fw0xQjHopQZs7fN1u8bwrZOHdXYchyGZ'
    b'ReN73zpnex8cpqDsOg/Odj6hBRtjAjhrTIMDSClVAPeWDfIwUUpnaCndTR6QECKAEuLAQwfs'
    b'GfOgGKvKbViqSVkrp4qirjiZj4WMK3U8ny48W04lKc9znhJYn4sQitbnfvIBnOUQ19h/wFQA'
    b'AAAASUVORK5CYII=')

# ----------------------------------------------------------------------
stop = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABEklEQVR4nGNgGF7gRLi7/8lw'
    b'j6unIjxf48Inw93Pn4j0sMFqwLEQt1ef58/492PDiv+48Ifp/b+Ph7pfxm6An8vn78vm/38Z'
    b'Ho4T/1i1+P9hP+f/WA047O74+ev0yf9fuHvixN/mTP9/wN0BuwH7HW0+f+7q+P/Czgkn/tLX'
    b'/X+Pow12A/ZaW33+VFvz/4WJNU78qbHh/05rSxwGGJl8/lhZ9f+FuglO/LG29v9OY1McXtA2'
    b'+Py5peX/CzUTnPhzR8f/3doG2A04oKr7+Uv/hP8v9K1w4q9Tpvzfq6yDwwUyGm++TJ76/9vs'
    b'OTjx577+f0B1D7AacFBEOf2ojNbHUwY2/3Hhw5LqL/cJq/hjNWBAAADHhi17T5zQ9AAAAABJ'
    b'RU5ErkJggg==')

# ----------------------------------------------------------------------
robot = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE'
    b'AAAAAAAA+UO7fwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAAd0SU1FB9kJCxYLCNZwjAwAAALV'
    b'SURBVDjLfZJLaBNRGIXPvTNzk0kmM0kaU7XVgI9iRdpiK2oFHyutIuJKKOrGjW8UBd24sgtF'
    b'0IULceGiuBGUulB8bNRKlQoiqBXrow9DWm2btGmSicnM3HtdWdoS/dfffzjn/w9BhXl1sq2N'
    b'9n0/RoncSHRFox7P5yJWV0rVrx+83fN1NqtWErg/MtyRqE+spT4GoiqAECEuxPHM5E8bwPnZ'
    b'LJm/fGnT6gOFuOiczDHybTANHg3DmpjA8g11WOJMOj1ZfeXdF++S/3QwajthUhRkQU0tovEo'
    b'1KCELNWAmQqyw+MyYIX4fyM0tzbcfP7t3b70x6+b4HFksi5ipgqhUSQaraudnd0js3k6XyBX'
    b'VVhnGHoDBwd8BJG4Ci8AcFUgZEaO3rrc3lzxBvdunDEUkmrp+zR4yjSDe6am8wgwHVQh0FQK'
    b'LhwAFJ5QX2/ZvuOiL5R42rS+Xc5ECAa9LaYRfsg/0IE3vQOojoXgmhYIcSEEkE2n4QswhGPB'
    b'1qjJHv9IDSUAJGcEul/2sEIuLwmlRYUqkFIgk02BS4qgwSAgQSQwmSngwb0n0GOL+ZwbtDhs'
    b'6c5VjdNVYf9nAYAxFbzMOaMEvGSDaSo4l/AxBk7JeO3iFb/mfKHrbcYqfswaiXqi+C0LGRuQ'
    b'iqXkSi6E1CBBwIXAMkvBopr41O79F+Y6aE/Q4OHWRWrA7y+NjLsYGitgdKoEp1xA8fdvuI7E'
    b'UCqLfMGxW8KRut4j24w5DtytTd1lIpsCSXtC93nQmQIQikBARXbMA2UOlsZ1TNvuyLM7T+tM'
    b'LbgGQO+MwN5zdx4BeHTl7OYT8bCEoBQCUsBzxMK4qoIDPsYQi2ijzvefdb/83K1YpMIXp2v6'
    b'fdIZ7k9CKRabmlt3+a2yExvsT/L0+x/X7DG0haJGY1UUHypW2fg8sCSUd5md9lDSNHL0TAc/'
    b'XF9bXZMpKwtV53T90MDDQ32jz/7yfwCgMC4aIG/jfQAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
script = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAXUlEQVR4AaXOwRVAABDEUL3R'
    b'i0qUox3lAOS2I+C9nNZ8mmVZfhUPXT8sVQow5gmIAuWYprFdFEgB7AFoDshXBfgyzgBHKQBv'
    b'xxHgBSkAUgWA2DADdDN2gOz3BXjfCvJRwfdmZCaAAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
callback = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAW1J'
    b'REFUOI2Vk08rhFEUxn/n3jszaDIpJQsrK2xsJkvlC0iZIjsLNSkWNrIgRBILpCkLSmnKbHwF'
    b'K3+GUigbpSx8BMa8r2sx3jf3nT/y1K3b0zm/89xTV0RpAHpHNy3KYEVDSwfWJBAdBxXDigGl'
    b'edobFCIyweWrc4Cx4R6aY0IyoUklNKlmQ2uTprVJMb52Ee11AertitODG0QMJDtQJo7VBpE4'
    b'nsRATGPAdPcxgwt3NYsAztf7mW4E8PzK89rjtQGerxonKPk6NOeWC+F9eykDwKdftT8AQmyp'
    b'rBwj3dcFgJbKeS/rqmYnQVBgfgYVH19DoAiU/gJ8BAAFuZUM2cUCuZVKfCyMTO3z0vZsg/qT'
    b'jXFxAZ52iUB2sUBU6b6uMJ1TX/YkTMDPnKPVDFZALFzf3pM7e3KaXYCv2JoaAmBydheAy+ID'
    b'hzszoRfE/i0J/kJUE/N5G22YmM/X30E9SNSL7qBugr+AQYJ/AWrpG55JajgVEJtYAAAAAElF'
    b'TkSuQmCC')

# ----------------------------------------------------------------------
func = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAOVJ'
    b'REFUOI3dU6EOwjAUvNfxNSgy5CRumcFtBIlaSHD7iGKXZgJJ1gWDIXNI7IJCoPF8wkOQQjcG'
    b'iKG4pKJ99+7uvaREwkEXiE7dPxOQSrPrz7mN4Ppzlkq31gBASKW52B0QBl4rIQw8FLsD3omI'
    b'8+UKAEjiiGw3kyqJIwIAw2uiVx1PcAd9VOXTbbXessr3CAMPVZne68fTY6SagH1J4oik0o9m'
    b'426jKtPaW03A7COejKDyPaTS3BR5SWDHM8ucTcdkxADAHrOZAMtsw8NgwctswyQcNM+3eo3U'
    b'RvjUTMIB/clf6IIbugV+FcGm5JQAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
edit = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABXElEQVR4nJXTz0vCYBzHcf+y'
    b'OniqDgURUVIdMiUPdQisFUUpCRlhUIhp0CXIS4RSiTpyllCQMcJf2aBZrQxxiZiIDf201Y6m'
    b'2wNfHnjg9b48fDUaFQeAtdEQkuLNiKNVYyXsyDMJUFujuD60oV6tCOKbThW+cU4A91ZUH3wg'
    b'7eP4rlVrqnGTi3wJMQK1kAnU9jSU4+QGmm/RXyyQRhSDZgTMXf8H2mE+OI8Q0Y3SK9M6IGGe'
    b'Yzti8cy2xKX8C27d+j/MUepx3GOQ8UVFiM4pxjoJp30LqCc21WE5kAm7CHD0LgpZb5N/PEGO'
    b'suMzTCjC/QU2C9q/ho/MEYpsEKnLPdwdL3XGcoAm91fBxA/A50JIXbkR9S7jfKVXEdZKXzYz'
    b'NgCjQY90zIMzxxQCtkmU39n2WA6ET50WDA8NwmIaQcS1iOKTtHCgxelri+VAYsfYA9KzjnL+'
    b'WYIRNav6A7llxO2+1g0dAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
testrun = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABgFBMVEUAD28AE3AAGXP4+fwA'
    b'IHUAKHjv8/vz9vz5+vzm7frt8voAMXvl7fnp8Prr8frx9fvn7/rv9PsAOn/y9vsAQYL2+fwA'
    b'SIQAT4cAU4ghbZwmcp0rdZ8weqE1fqNLj7I5gqQ8haVVl7VfoLlqqb1ysMDc6+bP49tgrn1i'
    b'rn5lsYFxt4tztIsxkVMuh001lFc5kllCm2E9j1pFlWFNn2pRpG9VonBSnG1QmGpbqnhfrHtc'
    b'pHZZmXBosoNttId+vJS518RHnWR7dE9+dU6HekyDd02yqo2Rf0iMfUqcknGdhUWXgkawjz6s'
    b'jECnikKiiEO1oGnBsYi0kD3///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQCWFoAAAA'
    b'U3RSTlP/////////////////////////////////////////////////////////////////'
    b'////////////////////////////////////////////AGaJflkAAACvSURBVHicZc/XDoJQ'
    b'EEXRQRHEBqKIXQEvVuy9i12x3f//GKWEkLgedzLJGcA/Hw+wQtBlh7u/gfy2O6R/wRBWSLAZ'
    b'IIoYP+gqMtGIfkCqnMIvdjyd1epLdsw+IVkpJd/UkHJcgVeUAp9Yq6aQGrpBWJblfHjT3Q5G'
    b'81gvdoKAJOUC8WbUcQaymCWPXNs64VRuD76MD18YrdXpTxaMxhyAIDDWIy4dzO07D+sXr7/w'
    b'Ba1QLU9vbmThAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
timer = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAitJ'
    b'REFUOI2lk09IVFEUxr/33r3vTY1hi8JFUIEV1aYIwUUTblqYtEymf0KLCpFaNEYFLcLChVIT'
    b'UdRAQjEZg1CWtGjRQgmNLGtRZMIMkVY0MBPMU2deM733vhZ3mDLUFh747lncw+/84RxN0w0s'
    b'xcT/Aq4+Heb126NwbBvLqqtx8lg9Tu0JaZUATTfm1UgqydrmGCN3xzhp27Q9l6kfWbbHx1jb'
    b'HONIKklNNxYGbAjH+GZqijbJ3D/qfztBGb61MODdlzSHPqT5t61vusiMS2ZcMuuSobb7vNA3'
    b'SE3TDWzd101hGJBCh5ASphBK0oBlmejvCmNtUydGH52vtD49m0PD8TtqiGs2b0T1pi1YKYDV'
    b'VQI1KyRqghLrVlWh++YTAIApgLxTqgB0PQDOTCvAt4kk0slPMIUBKVV2KQyYpoBlmmrY0sRM'
    b'3qkAXM+BHgyqGSR6Wul4nCuXLHhkoqeVJDmedbi95RrHsw4/Zh02nEjwXPwZdQAoegI+gboD'
    b'UXhlX3cwChIouWpVLCnw8EYbAlLg/edJDGdy6DrSqOkA8LNkwvdVaZ4PvOiNqDJ9wCmZ+G7b'
    b'0EDkCzkcOtOH/d2DeN65+88m5osW3HJvBLDzcBQjvREQQKFkYeDVV3RcGQCDy3H2aD1e7t2l'
    b'hR5gLsBnuYIyaEfLZbyOn8Zs0UJ747bK6rY/nucW8r8C8AEM3YvAp/IA4Jf/FjMBqD4vdUQB'
    b'qERauRX1mosCtKWe828hCBpO4ECmngAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
signal = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA0ElEQVR4XsVTvcmFQBCc77zQ'
    b'nxasQbharEOwC+3BCkxNTcyEi8UCLEBBRA7uYxdckBc9X+DAOOMwe4F7/p3n6fEDFMmrB+h5'
    b'njGOI57AGANNw2TCMMS36Pseikwcx0iSRJimKSkV2A/DIHlVVdJjNE3jl2Xx27YxATDZ3/XD'
    b'0yxvIQgC4b7vFInvuk7eoyhCWZbSlS0opW68smmakOc5rLWcH8eBuq5vPc0PrZkXrizLMrKs'
    b'zjnOiqKQrnyDdV39E9CsphW2bfv4Hrz/L7x/wD/EwKNnvVMJFwAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
list = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAARUlEQVR42mNkoBAwgoiGhob/'
    b'pGoE6gHrZSRHM7IhYAPq6+tJ1tzY2EgDA0CCIDaIxgWQ1Y66YHi6gCwDQByKMhPJVqMBAL9M'
    b'cRGlpGcIAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
message_go = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACSElEQVR4XsWTzUtUbxTHP8+d'
    b'e2ccHR3HyWkcq5+kDaS5ELWNBUFW5C7B2vSyDalI6h+IqE1RJLkwoqBdy6AoWocLF4mL2pVG'
    b'hC/5Mj9n5s7Mvc9LOBdEF65a9DmL7zlw+HIOhyOMMfwNFvBvDcTEu6/GlxqtDcqYqmoDqqpB'
    b'HeTs6DGAMWB7vqKnfT8Dh+P4BtDb7UEQUCq7rORW2Jc+QNSBH8se429nsaU29HbE+TCzRn9H'
    b'DOwwUhoEO9E6TDSWYbP/05f/aU7UAGArZbBD0JdNMPNtnWxLlHh9lLJv2O6Sd/NMz76h479u'
    b'Eoku2tOBgSWDfdAaeg418XPVY35xg/oaiYUiJDSOpUk1Rnny6im5jQWQ8/hSA2BLpRGAMYpi'
    b'yRCvcxAhC9vycQuLNDU2U6mUWFhbxYkbxj8+5OrgNSxhcEICW+lgX7dSZq2gaNsbxxgAl6HR'
    b'03Sf6ARMNbpPZYmlI7z8PMFI4QqXB89gSxWcaGHdJduaxGhDQHCmgeF+ACpemWIpT76YI5mN'
    b'MTn1mEslL7hCxdccbW8g7AgsIQBwPdBaszT3m0jEwVcexvGRSuK5PuUNn8WVJcTY82lPCByl'
    b'fEJ2CIwFwN2LXZy/NUIsXgsClFbk7GVaOpPMzfxi9ORteo8cY+uZDp5tswDz/f28ASiU8y8K'
    b'bvG4UjIEUFdfl+m/0Gel0knnwY1HXsuezFQqmRra9RtdzyUAjKWrMnz9HJN3nklfehOZVOtN'
    b'AJtdqA3XEgBFWQDg3tj98YZYw1QkHHlNAH8A8AEiP3y9+wQAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
message_reply = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACT0lEQVR4Xn2TvWtUSxjGf/Ox'
    b'OZvdkxs2l/WLaMIFUaIpLAXlVoIQULBIZWFhIRbGf8DKzkrTCjEgCMrCJkIs7BRFREWxSZok'
    b'oiFmA5vPTdw9HzOegQyri/iDBw7nPfM873tmRkxMTLwPw3DAWmsAhBB0ktWc2CPXaDSelcvl'
    b'yzgqlUrdZqRpao0x9s+4emJbrZaNoshOTk6+rVarTE9PI4EEIDNwIjPxae1UC1FskVL6DhML'
    b'BNIg2cMt9HJGSZLuFSyVV9958rqGktL7UVCGue0i0id5+Q6ktAhrmPq8xnisaXYphJRorShq'
    b'Yz9thdybP4wG8CYerSRSwNN3a9xqddPYrynW66xvtjDCsLAVqPFaf5cWJBr4bWYhwCRplrzF'
    b'7dU8KwMh4UbKgy+ShyvbDB0I2Dz0f2giOyaEeaEBPzcOJST3X9a5uxiy3JMn/NhgJ9a8ESXs'
    b'doooKJIoX4hkayhSuVnt53ZyOJ/evKFvdZ3aUswuGyhhKecsSWoIZEi3tKLUjIUBITvnTw2M'
    b'ngoZ/W+Zoz+WsD3/ki8qLh603DgdMnKiwJHm7DeT04+CvJrVv26jEAKDYcdqrpwbJIrnebyQ'
    b'dVLqYfg4XD1TAhR3PtR2F26efw4gO3+iP86iK+RaZnJpeJ3B2lc2mhYTW9LUMhAayR6yc//b'
    b'50Bign+4fnYfIydj+kNFlLpvoWkUHs1f0IGGoI+xC70IncMY3yFUp6YoatBCCCecHC7Zj9F+'
    b'VkhXb79TAteJRGdXc25mZuaYMSb2C71BB940SJJk0dd/AlB2ZqpLY9f2AAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
msg_signal = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA0ElEQVR4XsVTvcmFQBCc77zQ'
    b'nxasQbharEOwC+3BCkxNTcyEi8UCLEBBRA7uYxdckBc9X+DAOOMwe4F7/p3n6fEDFMmrB+h5'
    b'njGOI57AGANNw2TCMMS36Pseikwcx0iSRJimKSkV2A/DIHlVVdJjNE3jl2Xx27YxATDZ3/XD'
    b'0yxvIQgC4b7vFInvuk7eoyhCWZbSlS0opW68smmakOc5rLWcH8eBuq5vPc0PrZkXrizLMrKs'
    b'zjnOiqKQrnyDdV39E9CsphW2bfv4Hrz/L7x/wD/EwKNnvVMJFwAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
node = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAM1J'
    b'REFUOI3VkqEKwlAYhb87xWDyAWwrvoMWV7TKNNgNgm1lyWRaWRPFZJ8mMcyw4jMIFov4AAui'
    b'oM5rEMPVCYNh8LT/wPn+E44QWoY00lKl/wvgD3XpD3X57meTBAEM03ne2LLW2wkFEEd+yTAd'
    b'grmteGOrIAG6biiyANV6Jza8Wkw45w1Khss5XwEgiiRdN1QbLGejWICQoJ02bAOLcnMKwO0S'
    b'fTZo2HsRSwC8a1sC5I7rJ+B6VxqIpEv0BkUJ0OoflGeJAd/0R0v8GeAB5NE/VGca4L8AAAAA'
    b'SUVORK5CYII=')

# ----------------------------------------------------------------------
main = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAACjlBMVEUAAABbnzdaoDlaoThZ'
    b'njhaoDdEREBEREBZoDdZoDlEREBEREBEREBcojlaoTdToD9EREBEREBYnzlShjxEREBEREBE'
    b'REBaoTlVhTpaoDlYoDlYoTlViDpZnTlanjdanzlaoTlaoTlanzlbnjhZnDlYnzlVqlVXoTUA'
    b'/wBbnjlYoDdXmjlWmDlYmTpaoDlaoTlYmjlcojhaoDhaoDlYmDpLb0BZmjlYoTlanzlXnDlY'
    b'oDlZoDhZnzhYmjlXmTlYnDlXmjpXmjlanzlZnzhXnDdYmThLSzhZoDlZnjc/UTxWiTtDX0BW'
    b'nTdanzlanzdaoThaoDhYmjlYmTlanzdWlDhZmTxaoTdanzhUqThZmjlZoDhaoDlYoTdaoDla'
    b'njdYmThYmDhanzdaoTlanzdYnzlaoTlXnjRaojhYmzlXlDlVjztRlC9aoTlmmTNaoDlXoDpV'
    b'qipYnjlaoDdXjzpKSjlVkjpanzlaoThaojlcojZanzc/vz9ZoDlYmDpNWj1Amj9aoTlYnjlT'
    b'hjtVijlZmzhYoDlZlTBanzlZnzpXmjlbnzlaojdZoDlYoDdWjjpUizpXmjlZmTlKZjlYmThM'
    b'WD1ZmzhYoDhXlzlZmTlYmTlWkDtXlTpZoDlKbD1ZmzhaoTlVhjlZnzhYoThboTlYoDhMc0BY'
    b'mDpYoTlYojdYnDxZoDlZoDhYojdanjdSdT9XlzpbnzlVqj9YnzdZnjdZoDhbozhXlTlbozZV'
    b'lDhZmThZnDlYnzdYoDdXmzhXmjhZojhboDpaoDlRgzpYlTlanjlanzlZmzhYmjlYoDlbnTZZ'
    b'oDhUhD5YnDhaoDgmlyRboz1boDhboThIkUhaoTlZnzlZnjlZnTlZnDlZmzlaoDkPTjfrAAAA'
    b'03RSTlMAQGZoajMDBJ13AQcILPgNCgtLLg8NAkwxTK3SL077jeeTbiVP4wMmATXy7Z+dmZi4'
    b'JHntnhv+/cD90tDQ0tPlw+D+o/CrD2vhDkERKuvzrK2wscZyI+WVCfms6Pe6uLy8uNH89N8d'
    b'dsJxQwjiBXwjBrvlTRFMfYhrIfsEr68SBqHjKz/WnA3ZU9djYGHPRUL1xhGzFN6+fPmEXV6/'
    b'FtntLJXHYscZizFFE6V6N8Ycf0MM6SWMMnQqM7vh4ODi4k1G5yxn/sjrvv0ioiOucQIZUV8H'
    b'yTvKsQAAAjxJREFUOE+Fk1tIVFEUhv9vZjjJhAQZM/ggRUl0gYqkiILoIpQQIUJQSIYgRvRg'
    b'Bt0QoaALaVAJQXYhqCiLooKoIedFpCiMBqMHiSSCepmHAskptsdZPZyZcYaM1tPP/s9mrfWd'
    b'f6P/FJIAIVnhxCw8IcnDnJDKhiSwvB+o1b+iYJYRKn8lhaXJwM+rdYC5jIRmDyiChZwkedmC'
    b'WgukJaF4Mhz6289unCQdjFTZHyLktIVEsU+tS+dmrkqwFfg8/3mxb9tGJSnqo+rH1kChJMlC'
    b'fRbamZIUxUdVz6Q978oX3t79Jegas3ncck0pKeZ8hypfSC2MPaQ5uA9wxakppZj5bhzFk5K8'
    b'7D4ul2zSlIqZ+S6D4km1AXCuZNOmb2aMZ4TiSR0KBny7SoCZRY5L9WMG6QCUIp0DG+g8eU8x'
    b'M0hrZ/qit/l3MckTcFRnAczCEu3TkLxwQP8mGe5u64GDU/554FIRyV4AWvP+jRzVMwWSd7sn'
    b'Omi8A740VgGww0kt2+nKk3zKz0aekMsf1AWdEhybIlno/wJqnSQNAu0ByZL5B1nvJOkNR7r4'
    b'dArFk6X7vWZlivunh2nrqXEfdqG+paWZfM/ikR0PoPXqEqfRevSE6pJMfmRux97mmqGbC5z0'
    b'tQ4pMZUkLEuYCn2n4RGzpN7kCPK8iJdLUvD/Fl2fk/0BMyUtL/PRjIhlin3pzeHeoOevDfjI'
    b'i2QkKeoFL0mKev3svya9XcYm36Ggci8xr17CiuE1YOP5DzzMTav+AFzuGWnDJ5QpAAAAAElF'
    b'TkSuQmCC')

# ----------------------------------------------------------------------
ldf = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAaUlE'
    b'QVQokWP8//8/AymAiSTVCA3Km3yVN/luey5HkEuyDSwQarLpRWRRfNz/MKC00ec/EsDFJdlJ'
    b'jP///1fe5Euk6rt+mxn+owL8DiPHSSgaIG5DDn5kLhYNxAAWZA7+2IAARnolPuIBAMlyfBM8'
    b'gi6iAAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
table = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAsVBMVEUAAACBjaSosMBico9g'
    b'cIxoeJSKlqu8xNPGzdpbbIleb4tre5ZsfJZ3h6CGlKqCj6WEkaaYpLeqtMS7xNPBydZldpBv'
    b'gJlzhJ1/j6aDkqiMma2Sn7KPnK+VorWcqLmtt8a2wM+5wtDAydbEzdrDzNl4iaB7jKOAkKaD'
    b'k6mDk6iHlquLmq6ksMCmssK0vszI0d1xg5qHlqmwu8jEz9zG0NzGz9qwvMmvu8iQoLDEz9r/'
    b'//88uj47AAAAAXRSTlMAQObYZgAAAIJJREFUeJxjYCACcHKxMIuy8oiJ86pJSIIELExUlJgU'
    b'9czlhXR1NMEqGPkF+NikZKRlBeU0QALaVlZW+lYQoA0WUOawtFS2tDS2tDQFC2gBZUSgKgxB'
    b'AurswkAIAeogAVWgjDBUhSpIwMDIzEjYCAIMQALcQBkFqApusDuQATFeQwcAOqgUTQWb0KkA'
    b'AAAASUVORK5CYII=')

# ----------------------------------------------------------------------
slot = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA8ElEQVR4nM2SzQqCQBDHd7Ov'
    b'U3T20qEHVAQfoI6dtKNHoUCR/MCeoyfxVIjixzaztaJEZF5q4McsO+x/Zv+7hPxNKIoyVVWV'
    b'apo213V9BswNw5iI+tlcs/O+S0fANE3qui71PI9EUYSMQYDXTrsVq26XB9cnsMb99gQSTDCC'
    b'CQh0HwFLEFiI+mErM8ER2cjdCeI4JnVdCygCe1JvD8IwpFVVteFX6R2+79OiKGhZlg1BENDe'
    b'AmAiE0BnjuM4DbZtcyzL4rwIgGn8EOY8z9+SJMlngSzLOF8JwDMy+AcMc5qmnMECg66AB9FA'
    b'zINM/FncAe/dZnGxg2H+AAAAAElFTkSuQmCC')

# ----------------------------------------------------------------------
flex = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAL5J'
    b'REFUOI2lU0sOgkAMfZ3hMhB2rLwKQXHpEQwHIB5B3fmJt3FngMtoXZXAdBxJpkmT9rV90zYd'
    b'ImMRI0koePy8WeydsTT1BQsSSJLPF7IEAPruxW5hmuWzRLdQ/LGDQ9vOCOqqZFxvwQ7UCJf7'
    b'Y5a8AlRnrphQ8NfrU5vIWO8Olkia5URyB3VVjiT7plE78WEAADJW6TD0vN2s+R9GxmoCLsBc'
    b'gE8AhzDR4BKXiLrE81Mn+bBxBbGfKXqEaIIvnxpNfNep63EAAAAASUVORK5CYII=')

# ----------------------------------------------------------------------
array = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAMAAABrrFhUAAAABGdBTUEAALGPC/xhBQAAACBj'
    b'SFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAB3RJTUUH5goYECcf'
    b'mD8pDgAAAiVQTFRFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAYHYnDgAAALZ0Uk5TAAECAwQFBgcICQoLDA8QERITFBUX'
    b'GBkaGxweIiMkJicoKSorLi8yNTY3OTo/QEFCQ0RGR0hJTU5RUllaW1xdXl9hYmNlZmdrbW5v'
    b'cnN0dnd6e3x9fn+AgYKDhIWGh4mKjI6PkJGUlZaYmZqcnZ6fo6Slpqesra6vsbK0tba3ubq+'
    b'v8LDxMXIycrLzM3Q0tPV1tfa29zd3t/g4eLj5OXm5+nq6+zt7u/w8fLz9PX29/j5+vv8/f47'
    b'h/m/AAAAAWJLR0S2qgcL8QAABnxJREFUeNrt3etbE0cUB+AJIdwEFIQsVYspFYqCgAoKSjTF'
    b'SwvWVkMxtdVCrS22EmOpoaR0Qcq19oI2FKg3lDsohEAyf18/NDwC2SUxGWen5Tffz9kzL7vZ'
    b'3bPPwyGEEEKIwVj8+c8TNJJ196ea/HQd4b506fkfto5HVLK77+MSybA6WWZl+3Ma+ZptPpTC'
    b'e/8pJc2zUZTsuWPJfJnM5HhKo1tP6iS++5fqhqMsearJtJIsx0WjXtN2E8/9m+zTUZfsdeUE'
    b'krm80QNQT8NWfvvPaPIwKNnrMhFCSGYTi/1TSmtjee0/tpZNxfRGGiEGyxSjbJPZvACyJxmV'
    b'/NRsIFInZbWu8wK4xqzkHzNJiYdZtpEMTifAELOSZ4pIHbNkdLqSD4Blhl3N9aSfXTLPVU5X'
    b'wCK7mrvIILtk/h/4AMjsSqYThGEyKv/3ACgAGObyt/ABaPELCjBv4wNwaV5QgPEiPgAHxwUF'
    b'6N/GByC5T1CAM7wehWvEBLiXxgtg+10BAfyPCrg1BnUHHvpFA/D/aUnk1xCJNw/5xQLwDZg5'
    b'7p+Q1JO/LQsF0HyA6/4JSdzfIg7AXNvRjBjebfEYydIz91oBhm+Ft6rLJL0G30UI0emliuqr'
    b'4RU5HAHALfI/WrcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVpZuS9bhy22ybD+fl2oIMyQhrdTmlGWnrTQtIcx/'
    b'TW1IzTtvl+W2y4ezknQiASTtuz4WCFvqPrUrHIK4XJs78A/il9223Lhwtr/rVPdS4DBjX+5N'
    b'EgfAeM69KnCho1wfMiSlqnf1wXqrQm9HX96xsCrEfc4oCsDb36ybfuY+GR8iZOvF0bUhoxdC'
    b'DayMf8+9NmSmMVsMAOP1oLk/I8dC/P0vBo34nbgQ4hw49nB9yItGowgAyZ8FD3/z3y/b6Dcq'
    b'rmo0+HijVRv9DujK7gcP1Vj8NFkAgJIFpejbWRtsJrdXKaQ3dwO0N1qUQiaLtQcwtCpGPzuh'
    b'fitIsCkf0ZagfpR3lSejtho0B8hTGf/oUJ+/meZWDnGrDyrKcCiHzORpDmBdUg4f2aMaUqYy'
    b'IGa5UDVkz4hyiPes5gAdKgN/fGbVh4FP1A6pOq1Ob/YpR/jbtQZIUJ16Va06h9mpFuJUi4it'
    b'Vgu5m6AxwM4Btfgrqnc11YmRqhMr466ohQzsBAAugU39I9ih+V3grHeT3wbzZrV8EJrV/kHI'
    b'4FKMHmP8KHxiTDHEpf2jMKeXoazbSiFTArwMKb8O/1G8eV6HibHxxas2RJKswQ0Ra6iGyCNB'
    b'GyKE7G5c90Y4GLolZl3fErOGbokNrm+J7Ra1KVoRuimaFEFTtELUpighSXsbHq+0xXtOv762'
    b'+OmelZfvxw0itcUJ0SVKR6xtsnzzlT6MFP77YaTwlT6M3JTlNusRKVGoDyP4NAYAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    b'AAAAADQFGHKEtb6oLpf0Oi02pdNLpe+HV6RjKAKA8Ndct8UYw3v7Mcaj7YsMimcBQCl17k/k'
    b'u//EAy1sKmcEsPz7mVSu+68c8AkFQOnf5niO+z855KeCAfgf7OP2U6greMyqbHYAlP6ynRdA'
    b'2j0qIgCt4QVwmooJ0JfMZ//b+gUFGD/IB6BoXFCA+Ut8AGzzggL4nHwAnD5BAdQnRrJdMgUA'
    b'Q4DJzQ0wSLrYJVu8xgfg2iK7mjtJPbtk08f5AByfZlezlRQ/Z5bsrx18AHY8YFayp4AYO5hl'
    b'43QFEHKT3RUgEYP5GaNkU9m8AHKmWJVsMRCS6WCU7YNYXgCxtWwqXrIbCSHE5PKyeA7+Kp1f'
    b'QyT9aw+Dkr0uU+CMci1Ffwf49k2eLbG37AzuBK6clXQme7QX1fB5iW9TVKp7EmXJz26YXqYz'
    b'WjqjOafGvivewrstnnLo+9koSp5pM6+Zc22QSur6ByPrArg+eiddgy8juvT8GvnXiEqe7Kov'
    b'ygxMBv0HI+YI9pM1NBAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTAtMjRUMTY6Mzk6MzEr'
    b'MDA6MDA3QzdDAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEwLTI0VDE2OjM5OjMxKzAwOjAw'
    b'Rh6P/wAAAABJRU5ErkJggg==')

# ----------------------------------------------------------------------
camera = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAAz0lEQVR4nO2UzQqCQBSFv73SM2TvobnMXiKDfpaB0L5l7yJKz1QP0XJCOIGQmjlTLerC'
    b'geEeOd94dQZ+oQ6AadHxneHmVcgcuPQINE9UZSRNABfhRjo3AYxjPVTXwzkQAp4UAYUrwE7+'
    b'BNhIgXqZLSCXtwSutX61TuWVNoBQO6+H1yHVm0xtAB6w7RjDGvBtAL5m3gZYASMbQNRjRLEN'
    b'oJCXNnzkhbyT7W+ayQ8080pj9fauDlqpUdwPWtyx80EAM0Cfv+wSGS7CZ02Af32nbm1tIkpl'
    b'g/wTAAAAAElFTkSuQmCC')
